<template>
  <main class="app-shell">
    <AuthenticatedTopbar :user="user" section="collections" />
    <section class="content-wrap">
      <div class="page-heading"><div><p class="eyebrow">WORKSPACE / COLLECTIONS</p><h1>{{ t('page.collections') }}</h1><p class="muted">{{ t('collections.copy') }}</p></div><div class="sync-heading-actions"><button class="secondary-button" :title="t('files.refresh')" @click="loadCollections"><RefreshCw :size="16" :class="{ spin: collectionsLoading }" /></button><button class="primary-button" @click="openCollectionCreate"><UploadCloud :size="17" /> {{ t('collection.create') }}</button></div></div>
      <div v-if="error" class="alert error">{{ error }}</div><div v-if="collectionNotice" class="alert success">{{ collectionNotice }}</div>

      <section class="collection-section"><div class="collection-section-header"><h2>{{ t('collection.my') }}</h2><button class="icon-button" :title="t('files.refresh')" @click="loadCollections"><RefreshCw :size="17" :class="{ spin: collectionsLoading }" /></button></div><div v-if="collectionsLoading" class="empty-state"><LoaderCircle :size="24" class="spin" /></div><div v-else-if="!collections.length" class="transfers-empty">{{ t('collection.noCollections') }}</div><div v-else class="collection-grid"><article v-for="item in collections" :key="item.id" class="collection-row"><strong>{{ item.name }}</strong><small>{{ item.uploadCount }} / {{ item.maxUploads || t('collection.unlimited') }}</small><span class="status-label" :class="{ disabled: item.status !== 'active' }"><i></i>{{ collectionStatusLabel(item) }}</span><button class="icon-text-button" @click="viewCollection(item)"><Eye :size="15" /> {{ t('collection.viewFiles') }}</button><a class="collection-link" :href="absoluteCollectionUrl(item)" target="_blank" rel="noopener">{{ absoluteCollectionUrl(item) }}</a><button class="icon-button" :title="t('collection.copy')" @click="copyCollection(item)"><Copy :size="15" /></button><button v-if="item.status === 'active'" class="icon-button" :title="t('collection.edit')" @click="openCollectionEdit(item)"><Pencil :size="15" /></button><button v-if="item.status === 'active'" class="icon-button danger-icon" :title="t('collection.revoke')" @click="revokeCollection(item)"><Trash2 :size="15" /></button><div v-if="collectionDetails?.id === item.id" class="collection-files"><div v-if="!collectionDetails.files?.length">{{ t('collection.noCollections') }}</div><div v-for="received in collectionDetails.files" :key="received.id" class="collection-file"><strong>{{ received.originalName }}</strong><span v-if="received.remark">{{ t('collection.remark') }}: {{ received.remark }}</span><small>{{ formatDate(received.createdAt) }}</small></div></div></article></div></section>
      <BrandFooter />
    </section>

    <div v-if="collectionCreateOpen" class="modal-backdrop" @click.self="collectionCreateOpen = false"><section class="modal-panel share-panel" role="dialog" aria-modal="true"><div class="panel-heading"><div><p class="eyebrow">{{ editingCollection ? t('collection.editTitle') : t('collection.create') }}</p><h2>{{ editingCollection ? (collectionForm.name || t('collection.editTitle')) : t('collection.createTitle') }}</h2></div><button class="icon-button" :title="t('common.close')" @click="collectionCreateOpen = false"><X :size="18" /></button></div><form @submit.prevent="saveCollection"><label class="form-label">{{ t('collection.name') }}<input v-model.trim="collectionForm.name" maxlength="255" required /></label><label v-if="!editingCollection" class="form-label">{{ t('collection.expiresInHours') }}<input v-model.number="collectionForm.expiresInHours" type="number" min="1" required /></label><label v-else class="form-label">{{ t('collection.expiresAtEdit') }}<input v-model="collectionForm.expiresAtLocal" type="datetime-local" required /></label><label class="form-label">{{ t('collection.maxUploads') }}<input v-model.number="collectionForm.maxUploads" type="number" min="0" required /></label><label class="form-label">{{ t('collection.maxFileBytesMB') }}<input v-model.number="collectionForm.maxFileBytesMB" type="number" min="0" required /></label><p v-if="collectionError" class="alert error">{{ collectionError }}</p><button class="primary-button submit-button" :disabled="collectionSaving"><span>{{ collectionSaving ? t('common.loading') : (editingCollection ? t('collection.saved') : t('collection.create')) }}</span><UploadCloud :size="17" /></button></form></section></div>
    <div v-if="collectionResult" class="modal-backdrop" @click.self="collectionResult = null"><section class="modal-panel share-panel" role="dialog" aria-modal="true"><div class="panel-heading"><div><p class="eyebrow">{{ t('collection.create') }}</p><h2>{{ collectionResult.name }}</h2></div><button class="icon-button" :title="t('common.close')" @click="collectionResult = null"><X :size="18" /></button></div><label class="form-label">{{ t('collection.link') }}<div class="share-url"><input :value="absoluteCollectionUrl(collectionResult)" readonly /><button type="button" class="icon-button" :title="t('collection.copy')" @click="copyCollection(collectionResult)"><Copy :size="16" /></button></div></label><p v-if="collectionNotice" class="alert success">{{ collectionNotice }}</p></section></div>
  </main>
</template>

<script setup>
// CollectionsView 是"我的收集"独立页面（v014 #7）：复用文件页的收集管理逻辑
// （列表/创建/编辑/撤销/复制链接/已收文件），并带独立顶栏与路由 /collections。
// CollectionsView is the standalone "My collections" page (v014 #7): it reuses the file page's
// collection-management logic (list/create/edit/revoke/copy-link/received files) with its own
// topbar and the /collections route.
import { onMounted, ref } from 'vue'
import { api } from '../api'
import AuthenticatedTopbar from '../components/AuthenticatedTopbar.vue'
import BrandFooter from '../components/BrandFooter.vue'
import { currentLocale, t } from '../i18n'
import { Copy, Eye, LoaderCircle, Pencil, RefreshCw, Trash2, UploadCloud, X } from 'lucide-vue-next'

const user = ref(JSON.parse(localStorage.getItem('filebox_user') || '{}'))
const collections = ref([]); const collectionsLoading = ref(false); const collectionCreateOpen = ref(false); const collectionSaving = ref(false); const collectionError = ref(''); const collectionNotice = ref(''); const collectionResult = ref(null); const collectionDetails = ref(null); const editingCollection = ref(false); const collectionForm = ref({ name: '', expiresInHours: 24, maxUploads: 0, maxFileBytesMB: 0, expiresAtLocal: '' }); const error = ref('')

async function loadCollections() { collectionsLoading.value = true; try { const body = await api('/api/collections'); collections.value = body.data.items || [] } catch (err) { error.value = err.message } finally { collectionsLoading.value = false } }
function openCollectionCreate() { editingCollection.value = false; collectionCreateOpen.value = true; collectionResult.value = null; collectionError.value = ''; collectionNotice.value = ''; collectionForm.value = { name: '', expiresInHours: 24, maxUploads: 0, maxFileBytesMB: 0, expiresAtLocal: '' } }
function toLocalInputValue(value) { const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; const pad = num => String(num).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }
function absoluteCollectionUrl(item) { return item?.url ? new URL(item.url, window.location.origin).href : '' }
function openCollectionEdit(item) { editingCollection.value = true; collectionCreateOpen.value = true; collectionResult.value = null; collectionError.value = ''; collectionNotice.value = ''; collectionForm.value = { _id: item.id, name: item.name || '', expiresInHours: 24, maxUploads: item.maxUploads || 0, maxFileBytesMB: item.maxFileBytes ? Math.round(item.maxFileBytes / 1024 / 1024 * 100) / 100 : 0, expiresAtLocal: toLocalInputValue(item.expiresAt) } }
// saveCollection creates or updates a collection: edit mode submits an absolute expiry converted to UTC.
// saveCollection 创建或编辑收集：编辑模式提交转换到 UTC 的绝对到期时间。
async function saveCollection() { collectionSaving.value = true; collectionError.value = ''; try { let body; if (editingCollection.value) { body = await api(`/api/collections/${collectionForm.value._id}`, { method: 'PUT', body: JSON.stringify({ name: collectionForm.value.name, expiresAt: new Date(collectionForm.value.expiresAtLocal).toISOString(), maxUploads: collectionForm.value.maxUploads, maxFileBytes: Math.round(collectionForm.value.maxFileBytesMB * 1024 * 1024) }) }) } else { body = await api('/api/collections', { method: 'POST', body: JSON.stringify({ name: collectionForm.value.name, expiresInHours: collectionForm.value.expiresInHours, maxUploads: collectionForm.value.maxUploads, maxFileBytes: Math.round(collectionForm.value.maxFileBytesMB * 1024 * 1024) }) }) } if (editingCollection.value) { collectionNotice.value = t('collection.saved') } else { collectionResult.value = body.data } collectionCreateOpen.value = false; await loadCollections() } catch (err) { collectionError.value = err.message } finally { collectionSaving.value = false } }
async function copyCollection(item) { try { await navigator.clipboard.writeText(absoluteCollectionUrl(item)); collectionNotice.value = t('collection.copied') } catch { const input = document.querySelector('.collection-result input, .share-url input'); input?.select(); document.execCommand('copy'); collectionNotice.value = t('collection.copied') } }
function remainingLabel(item) { if (!item.remainingSeconds) return `${t('collection.remaining')}: 0`; const hours = Math.floor(item.remainingSeconds / 3600); const minutes = Math.max(1, Math.floor(item.remainingSeconds / 60)); return `${t('collection.remaining')}: ${hours ? `${hours}h` : `${minutes}m`}` }
function collectionStatusLabel(item) { const label = item.status === 'expired' ? t('collection.expired') : item.status === 'revoked' ? t('collection.revoked') : item.status === 'limit_reached' ? t('collection.limitReached') : t('collection.active'); return `${label} · ${remainingLabel(item)}` }
async function viewCollection(item) { if (collectionDetails.value?.id === item.id) { collectionDetails.value = null; return } try { const body = await api(`/api/collections/${item.id}`); collectionDetails.value = body.data } catch (err) { error.value = err.message } }
async function revokeCollection(item) { if (!window.confirm(t('collection.confirmRevoke'))) return; try { await api(`/api/collections/${item.id}`, { method: 'DELETE' }); collectionNotice.value = t('collection.revoked'); await loadCollections() } catch (err) { error.value = err.message } }
function formatDate(value) { return value ? new Date(value).toLocaleString(currentLocale.value === 'en' ? 'en-US' : currentLocale.value, { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '-' }
onMounted(loadCollections)
</script>
