<template>
  <main class="app-shell">
    <header class="topbar">
      <div class="topbar-brand"><BrandLogo variant="main" compact /><span class="slash">/</span><span class="section-name">{{ t('nav.files') }}</span></div>
      <div class="topbar-actions"><span class="user-chip"><span class="avatar">{{ user.username?.slice(0, 1).toUpperCase() }}</span>{{ user.username }}</span><LanguageSelect :user="user" /><RouterLink v-if="user.role === 'admin'" to="/admin" class="icon-text-button"><Shield :size="16" /> {{ t('nav.admin') }}</RouterLink><RouterLink to="/logs" class="icon-text-button"><ScrollText :size="16" /> {{ t('nav.logs') }}</RouterLink><button class="icon-button" :title="t('nav.logout')" @click="logout"><LogOut :size="18" /></button></div>
    </header>
    <section class="content-wrap">
      <div class="page-heading"><div><p class="eyebrow">WORKSPACE / {{ user.role === 'admin' ? t('files.workspaceAdmin') : t('files.workspaceUser') }}</p><h1>{{ t('files.heading') }}</h1><p class="muted">{{ t('files.copy') }}</p></div><div class="quota-block"><div class="quota-label"><span>{{ t('files.quota') }}</span><strong>{{ formatBytes(user.usedBytes) }} <em>/ {{ formatBytes(user.quotaBytes) }}</em></strong></div><div class="progress-track"><span :style="{ width: quotaPercent + '%' }"></span></div></div></div>
      <div class="upload-zone" :class="{ dragging }" @dragover.prevent="dragging = true" @dragleave.prevent="dragging = false" @drop.prevent="handleDrop"><UploadCloud :size="26" /><div><strong>{{ t('files.dropTitle') }}</strong><span>{{ t('files.dropCopy') }}</span></div><button class="secondary-button" @click="fileInput?.click()"><Upload :size="17" /> {{ t('files.choose') }}</button><button class="secondary-button" @click="folderInput?.click()"><FolderUp :size="17" /> {{ t('files.uploadFolder') }}</button><input ref="fileInput" type="file" multiple hidden @change="handleInput" /><input ref="folderInput" type="file" webkitdirectory directory multiple hidden @change="handleFolderInput" /></div>
      <div v-if="uploads.length" class="upload-list"><div v-for="item in uploads" :key="item.id" class="upload-row"><FileUp :size="18" class="upload-icon" /><div class="upload-main"><div class="upload-name"><strong :title="item.relPath || item.file.name">{{ item.relPath || item.file.name }}</strong><span>{{ item.status }}</span></div><div class="progress-track"><span :style="{ width: item.progress + '%' }"></span></div><small v-if="item.chunksTotal > 1" class="upload-chunks">{{ t('files.chunks', { done: item.uploaded.length, total: item.chunksTotal }) }}</small></div><span class="upload-percent">{{ item.progress }}%</span><button v-if="item.paused" class="icon-button" :title="t('files.resume')" @click="resumeUpload(item)"><Play :size="16" /></button><button v-else-if="item.running" class="icon-button" :title="t('files.pause')" @click="pauseUpload(item)"><Pause :size="16" /></button><button v-if="item.canContinue" class="icon-button" :title="t('files.uploadContinue')" @click="resumeUpload(item)"><Play :size="16" /></button><button v-if="item.failed" class="icon-button" :title="t('files.retry')" @click="retryUpload(item)"><RefreshCw :size="16" /></button></div></div>
      <div class="toolbar"><div class="search-box"><Search :size="17" /><input v-model="searchInput" :placeholder="t('files.searchPlaceholder')" @keyup.enter="search" /><button v-if="searchInput" :title="t('files.clearSearch')" @click="searchInput = ''; search()"><X :size="15" /></button></div><button class="refresh-button" :title="t('files.refresh')" @click="loadFiles"><RefreshCw :size="17" :class="{ spin: loading }" /></button><span class="result-count">{{ t('common.files', { count: total }) }}</span></div>
      <div v-if="notice" class="alert success">{{ notice }}</div><div v-if="error" class="alert error">{{ error }}</div>
      <div class="file-table-wrap"><table class="file-table"><thead><tr><th>{{ t('files.name') }}</th><th>{{ t('files.size') }}</th><th>{{ t('files.type') }}</th><th>{{ t('files.integrity') }}</th><th>{{ t('files.uploadedAt') }}</th><th></th></tr></thead><tbody><tr v-for="file in files" :key="file.id"><td><div class="file-title"><span class="file-icon"><FileText :size="17" /></span><strong>{{ file.name }}</strong><span v-if="isShared(file)" class="shared-mark" :title="t('files.shared')"><Share2 :size="14" /></span></div></td><td>{{ formatBytes(file.size) }}</td><td><span class="mime-label" :class="{ 'preview-mime': canPreview(file.mime) }">{{ shortMime(file.mime) }}</span></td><td><span class="hash-label" :title="`MD5 ${file.md5}\nSHA-256 ${file.sha256}`"><CheckCircle2 :size="15" /> {{ t('files.hashes') }}</span></td><td>{{ formatDate(file.createdAt) }}</td><td><div class="row-actions"><button v-if="canPreview(file.mime)" class="icon-button" :title="t('files.preview')" @click="openPreview(file)"><Eye :size="17" /></button><button class="icon-button" :title="t('files.share')" @click="openShare(file)"><Share2 :size="17" /></button><button class="icon-button" :title="t('files.download')" @click="download(file)"><Download :size="17" /></button><button class="icon-button danger-icon" :title="t('files.delete')" @click="remove(file)"><Trash2 :size="17" /></button></div></td></tr></tbody></table><div v-if="!loading && !files.length" class="empty-state"><FolderOpen :size="34" /><strong>{{ keyword ? t('files.noMatch') : t('files.noFiles') }}</strong><span>{{ keyword ? t('files.noMatchCopy') : t('files.noFilesCopy') }}</span></div><div v-if="loading" class="empty-state"><LoaderCircle :size="28" class="spin" /><span>{{ t('files.loading') }}</span></div></div>
      <div v-if="total > pageSize" class="pagination"><button class="secondary-button" :disabled="page === 1" @click="page--; loadFiles()"><ChevronLeft :size="16" /> {{ t('common.previous') }}</button><span>{{ t('common.page', { page }) }}</span><button class="secondary-button" :disabled="page * pageSize >= total" @click="page++; loadFiles()">{{ t('common.next') }} <ChevronRight :size="16" /></button></div><BrandFooter />
    </section>
    <div v-if="conflictPrompt" class="modal-backdrop" @click.self="chooseConflict('cancel')"><section class="modal-panel" role="dialog" aria-modal="true"><div class="panel-heading"><div><p class="eyebrow">{{ t('files.conflictEyebrow') }}</p><h2>{{ t('files.conflictHeading') }}</h2></div><button class="icon-button" :title="t('common.close')" @click="chooseConflict('cancel')"><X :size="18" /></button></div><p class="modal-copy">{{ t('files.conflictCopy', { name: conflictPrompt.existing?.name }) }}</p><div class="conflict-details">{{ formatBytes(conflictPrompt.existing?.size || 0) }} · {{ formatDate(conflictPrompt.existing?.createdAt) }}</div><div class="modal-actions"><button class="secondary-button" @click="chooseConflict('rename')"><FileEdit :size="16" /> {{ t('files.rename') }}<span>{{ t('files.renameHint') }}</span></button><button class="primary-button" @click="chooseConflict('overwrite')"><Replace :size="16" /> {{ t('files.overwrite') }}<span>{{ t('files.overwriteHint') }}</span></button></div></section></div>
    <div v-if="shareFile" class="modal-backdrop" @click.self="closeShare"><section class="modal-panel share-panel" role="dialog" aria-modal="true"><div class="panel-heading"><div><p class="eyebrow">{{ t('files.shareDialog') }}</p><h2>{{ shareFile.name }}</h2></div><button class="icon-button" :title="t('common.close')" @click="closeShare"><X :size="18" /></button></div><form v-if="!shareResult" @submit.prevent="createShare"><label class="form-label">{{ t('files.shareExpiresHours') }}<input v-model.number="shareForm.expiresInHours" type="number" min="1" required /></label><label class="form-label">{{ t('files.shareMaxDownloads') }}<input v-model.number="shareForm.maxDownloads" type="number" min="0" max="100000" required /></label><p v-if="shareError" class="alert error">{{ shareError }}</p><button class="primary-button submit-button" :disabled="shareLoading"><span>{{ shareLoading ? t('common.loading') : t('files.share') }}</span><Share2 :size="17" /></button></form><div v-else class="share-result"><label class="form-label">{{ t('files.shareUrl') }}<div class="share-url"><input :value="shareAbsoluteUrl" readonly /><button type="button" class="icon-button" :title="t('files.shareCopied')" @click="copyShare"><Copy :size="16" /></button></div></label><p class="muted">{{ t('share.expiresAt') }} {{ formatDate(shareResult.expiresAt) }}<span v-if="shareResult.maxDownloads"> · {{ t('share.availableDownloads', { count: shareResult.maxDownloads - shareResult.downloadCount }) }}</span></p><div class="modal-actions"><button class="secondary-button" @click="openSharePage"><ExternalLink :size="16" /> {{ t('files.openShare') }}</button><button class="secondary-button danger-action" @click="revokeShare"><Trash2 :size="16" /> {{ t('files.revokeShares') }}</button></div><p v-if="shareNotice" class="alert success">{{ shareNotice }}</p></div></section></div>
    <div v-if="previewFile" class="modal-backdrop" @click.self="closePreview"><section class="modal-panel preview-panel" role="dialog" aria-modal="true"><div class="panel-heading"><div><p class="eyebrow">{{ t('files.preview') }}</p><h2>{{ previewFile.name }}</h2></div><button class="icon-button" :title="t('common.close')" @click="closePreview"><X :size="18" /></button></div><div v-if="previewLoading" class="empty-state preview-state"><LoaderCircle :size="28" class="spin" /><span>{{ t('files.previewLoading') }}</span></div><p v-else-if="previewError" class="alert error">{{ previewError }}</p><img v-else-if="previewKind === 'image'" class="preview-content preview-image" :src="previewUrl" :alt="previewFile.name" /><video v-else-if="previewKind === 'video'" class="preview-content" :src="previewUrl" controls></video><iframe v-else-if="previewKind === 'pdf'" class="preview-content preview-frame" :src="previewUrl" :title="previewFile.name"></iframe><pre v-else class="preview-text">{{ previewText }}</pre></section></div>
  </main>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { api, clearSession, computeFileSHA256, localizeError } from '../api'
import BrandFooter from '../components/BrandFooter.vue'
import BrandLogo from '../components/BrandLogo.vue'
import LanguageSelect from '../components/LanguageSelect.vue'
import { currentLocale, t } from '../i18n'
import { CheckCircle2, ChevronLeft, ChevronRight, Copy, Download, ExternalLink, Eye, FileEdit, FileText, FileUp, FolderOpen, FolderUp, LoaderCircle, LogOut, Pause, Play, RefreshCw, Replace, ScrollText, Search, Share2, Shield, Trash2, Upload, UploadCloud, X } from 'lucide-vue-next'

const router = useRouter(); const user = ref(JSON.parse(localStorage.getItem('filebox_user') || '{}')); const files = ref([]); const total = ref(0); const page = ref(1); const pageSize = 20; const keyword = ref(''); const searchInput = ref(''); const loading = ref(false); const error = ref(''); const notice = ref(''); const dragging = ref(false); const uploads = ref([]); const fileInput = ref(null); const folderInput = ref(null); const conflictPrompt = ref(null)
const shareFile = ref(null); const shareForm = ref({ expiresInHours: 24, maxDownloads: 0 }); const shareResult = ref(null); const shareLoading = ref(false); const shareError = ref(''); const shareNotice = ref(''); const previewFile = ref(null); const previewLoading = ref(false); const previewError = ref(''); const previewUrl = ref(''); const previewText = ref(''); const previewKind = ref(''); const sharedIds = new Set(JSON.parse(localStorage.getItem('filebox_shared_ids') || '[]')); const chunkQueue = []; let activeWorkers = 0; let workerWake = null
const quotaPercent = computed(() => Math.min(100, user.value.quotaBytes ? Math.round((user.value.usedBytes / user.value.quotaBytes) * 100) : 0))

// loadMe refreshes the current user and quota snapshot, clearing the session on authentication failure.
// loadMe 刷新当前用户和配额快照，认证失效时清理会话并回到登录页。
async function loadMe() { try { const body = await api('/api/auth/me'); user.value = body.data; localStorage.setItem('filebox_user', JSON.stringify(body.data)) } catch { clearSession(); router.push('/login') } }
// loadFiles loads the file list for the current keyword and page.
// loadFiles 按当前关键字和页码加载文件列表。
async function loadFiles() { loading.value = true; error.value = ''; try { const body = await api(`/api/files?page=${page.value}&pageSize=${pageSize}&keyword=${encodeURIComponent(keyword.value)}`); files.value = body.data.items; total.value = body.data.total } catch (err) { error.value = err.message } finally { loading.value = false } }
function search() { page.value = 1; keyword.value = searchInput.value.trim(); loadFiles() }
function handleInput(event) { queueFiles([...event.target.files]); event.target.value = '' }
function handleFolderInput(event) { queueFiles([...event.target.files]); event.target.value = '' }

// collectDropFiles walks browser directory entries and falls back to File.webkitRelativePath when unavailable.
// collectDropFiles 递归读取浏览器目录条目，不支持条目 API 时回退到 webkitRelativePath。
async function collectDropFiles(event) { const items = [...(event.dataTransfer?.items || [])]; if (!items.some(item => typeof item.webkitGetAsEntry === 'function')) return [...(event.dataTransfer?.files || [])].map(file => ({ file, relPath: file.webkitRelativePath || file.name })); const result = []; async function visit(entry, prefix = '') { if (entry.isFile) { const file = await new Promise((resolve, reject) => entry.file(resolve, reject)); result.push({ file, relPath: `${prefix}${file.name}` }); return } if (!entry.isDirectory) return; const reader = entry.createReader(); const entries = []; while (true) { const batch = await new Promise((resolve, reject) => reader.readEntries(resolve, reject)); if (!batch.length) break; entries.push(...batch) } for (const child of entries) await visit(child, `${prefix}${entry.name}/`) } for (const item of items) { const entry = item.webkitGetAsEntry?.(); if (entry) await visit(entry) } return result }
async function handleDrop(event) { dragging.value = false; queueFiles(await collectDropFiles(event)) }

// queueFiles creates one resumable task per selected file and preserves folder-relative directories.
// queueFiles 为每个文件创建可续传任务，并保留文件夹相对目录。
function queueFiles(list) { list.forEach(value => { const file = value.file || value; const path = value.relPath || file.webkitRelativePath || file.name; const parts = path.split('/').filter(Boolean); const dirParts = parts.length > 1 ? parts.slice(0, -1) : []; if (dirParts.length > 1) dirParts.shift(); const item = { id: `${Date.now()}-${Math.random()}-${file.name}`, file, relPath: path !== file.name ? path : '', dir: dirParts.join('/'), progress: 0, status: t('files.uploadPreparing'), taskId: '', uploaded: [], paused: false, chunksTotal: 0, chunkSize: 0, error: '', failed: false, canContinue: false, running: false, sha256: '', pending: new Set(), controllers: new Map(), resolve: '' }; uploads.value.push(item); startUpload(item) }) }
function wakeWorkers() { const wake = workerWake; workerWake = null; wake?.() }
function removeQueued(item) { for (let i = chunkQueue.length - 1; i >= 0; i--) if (chunkQueue[i].item === item) chunkQueue.splice(i, 1) }
function enqueueChunks(item, indexes) { indexes.forEach(index => { item.pending.add(index); chunkQueue.push({ item, index }) }); wakeWorkers(); ensureWorkers() }
function ensureWorkers() { while (activeWorkers < 4 && chunkQueue.some(task => !task.item.paused && !task.item.failed)) { activeWorkers++; chunkWorker().finally(() => { activeWorkers--; ensureWorkers() }) } }
async function chunkWorker() { while (true) { const position = chunkQueue.findIndex(task => !task.item.paused && !task.item.failed); if (position < 0) return; const task = chunkQueue.splice(position, 1)[0]; const { item, index } = task; if (!item.pending.has(index)) continue; try { await uploadChunkWithRetry(item, index); item.pending.delete(index); if (!item.uploaded.includes(index)) item.uploaded.push(index); item.uploaded.sort((a, b) => a - b); updateChunkProgress(item) } catch (err) { if (item.paused || err.name === 'AbortError') { chunkQueue.push(task); continue } item.pending.delete(index); item.failed = true; item.error = err.message; item.status = err.message; error.value = `${item.file.name}: ${err.message}` } finally { item.controllers.delete(index) } } }
function updateChunkProgress(item) { item.progress = item.chunksTotal ? Math.round(25 + item.uploaded.length / item.chunksTotal * 75) : 25; item.status = t('files.uploading') }

// uploadChunkWithRetry uploads one binary chunk with an abortable fetch and exponential backoff.
// uploadChunkWithRetry 使用可中止 fetch 上传单个二进制分片，并以指数退避重试。
async function uploadChunkWithRetry(item, index) { const start = index * item.chunkSize; const end = Math.min(item.file.size, start + item.chunkSize); for (let attempt = 0; attempt < 4; attempt++) { if (item.paused) throw new DOMException('paused', 'AbortError'); const controller = new AbortController(); item.controllers.set(index, controller); try { const response = await fetch(`/api/files/${item.taskId}/chunks/${index}`, { method: 'PUT', headers: { Authorization: `Bearer ${localStorage.getItem('filebox_token')}` }, body: item.file.slice(start, end), signal: controller.signal }); if (!response.ok) { let body = null; try { body = await response.json() } catch {} throw Object.assign(new Error(localizeError({ status: response.status, data: body?.data, backendMessage: body?.message })), { status: response.status }) } return } catch (err) { if (err.name === 'AbortError' || item.paused) throw err; if (attempt === 3) throw err; await new Promise(resolve => setTimeout(resolve, 300 * 2 ** attempt)) } finally { item.controllers.delete(index) } } }
function waitForChunks(item) { return new Promise(resolve => { const check = () => { if (item.paused || item.failed || item.pending.size === 0) resolve(); else setTimeout(check, 80) }; check() }) }

// startUpload computes the checksum, performs instant-upload lookup, resumes missing chunks, and completes the task.
// startUpload 负责计算校验值、秒传检查、补传缺片并提交完成请求。
async function startUpload(item) { if (item.running) return item.running; item.running = true; item.paused = false; item.failed = false; item.canContinue = false; item.running = (async () => { try { if (item.taskId) { await finishExistingUpload(item); return } if (!item.sha256) { item.status = t('files.checksum', { progress: 0 }); item.sha256 = await computeFileSHA256(item.file, progress => { if (!item.paused) { item.progress = Math.round(progress * 0.25); item.status = t('files.checksum', { progress }) } }) } if (item.paused) return; if (item.file.size > 0) { const check = await api('/api/files/check', { method: 'POST', body: JSON.stringify({ sha256: item.sha256, size: item.file.size }) }); if (check.data?.instant) { item.progress = 100; item.status = t('files.instantUpload'); notice.value = t('files.instantUpload'); await loadFiles(); await loadMe(); removeUploadLater(item); return } } let init; try { init = await requestUploadInit(item) } catch (err) { if (err.status !== 409 || !err.data?.conflict) throw err; const resolve = await askConflict(err.data.existing); if (resolve === 'cancel') throw new Error(t('files.uploadCancelled')); init = await requestUploadInit(item, resolve) } item.taskId = init.data.taskId; item.chunkSize = init.data.chunkSize; item.chunksTotal = init.data.totalChunks; item.uploaded = [...(init.data.uploadedChunks || [])]; item.status = t('files.uploading'); await continueChunks(item); if (item.paused || item.failed) return; await finishExistingUpload(item) } catch (err) { if (item.paused) return; item.failed = true; item.canContinue = Boolean(item.taskId); item.error = err.message; item.status = err.message; error.value = `${item.file.name}: ${err.message}` } finally { item.running = false } })(); return item.running }
async function finishExistingUpload(item) { if (item.paused) return; await continueChunks(item); if (item.paused || item.failed) return; item.status = t('files.checking'); item.progress = 99; const completeBody = { sha256: item.sha256 }; if (item.resolve) completeBody.action = item.resolve; await api(`/api/files/${item.taskId}/complete`, { method: 'POST', body: JSON.stringify(completeBody) }); item.progress = 100; item.status = t('files.completed'); notice.value = t('files.uploadComplete', { name: item.relPath || item.file.name }); await loadMe(); await loadFiles(); removeUploadLater(item) }
async function continueChunks(item) { const body = await api(`/api/files/${item.taskId}/status`); item.chunkSize = body.data.chunkSize; item.chunksTotal = body.data.totalChunks; item.uploaded = [...(body.data.uploadedChunks || [])].sort((a, b) => a - b); const missing = Array.from({ length: item.chunksTotal }, (_, index) => index).filter(index => !item.uploaded.includes(index)); item.pending.clear(); removeQueued(item); updateChunkProgress(item); if (!missing.length) return; enqueueChunks(item, missing); await waitForChunks(item) }
function requestUploadInit(item, resolve = '') { item.resolve = resolve; return api('/api/files/upload-init', { method: 'POST', body: JSON.stringify({ name: item.file.name, size: item.file.size, chunkSize: item.file.size <= 8 * 1024 * 1024 ? item.file.size : 4194304, mime: item.file.type, sha256: item.sha256, ...(item.dir ? { dir: item.dir } : {}), ...(resolve ? { resolve } : {}) }) }) }
function pauseUpload(item) { item.paused = true; item.status = t('files.paused'); removeQueued(item); item.controllers.forEach(controller => controller.abort()); wakeWorkers() }
async function resumeUpload(item) { if (item.running) return; item.paused = false; item.failed = false; item.canContinue = false; item.status = t('files.uploading'); await startUpload(item) }
async function retryUpload(item) { item.failed = false; item.error = ''; item.paused = false; await startUpload(item) }
function removeUploadLater(item) { setTimeout(() => { uploads.value = uploads.value.filter(entry => entry !== item) }, 2200) }
function askConflict(existing) { return new Promise(resolve => { conflictPrompt.value = { existing, resolve } }) }
function chooseConflict(value) { const prompt = conflictPrompt.value; conflictPrompt.value = null; prompt?.resolve(value) }
function canPreview(mime = '') { const value = mime.toLowerCase().split(';')[0]; return new Set(['image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/svg+xml', 'text/plain', 'text/markdown', 'text/csv', 'text/x-log', 'text/html', 'application/json', 'application/pdf', 'video/mp4', 'video/webm']).has(value) }
function previewType(mime = '') { const value = mime.toLowerCase().split(';')[0]; if (value.startsWith('image/')) return 'image'; if (value.startsWith('video/')) return 'video'; if (value === 'application/pdf') return 'pdf'; return 'text' }
async function openPreview(file) { previewFile.value = file; previewLoading.value = true; previewError.value = ''; previewText.value = ''; previewUrl.value = ''; previewKind.value = previewType(file.mime); try { const response = await fetch(`/api/files/${file.id}/preview`, { headers: { Authorization: `Bearer ${localStorage.getItem('filebox_token')}` } }); if (!response.ok) { let body = null; try { body = await response.json() } catch {} throw new Error(localizeError({ status: response.status, data: body?.data, backendMessage: body?.message })) } if (previewKind.value === 'text') previewText.value = await response.text(); else { const blob = await response.blob(); previewUrl.value = URL.createObjectURL(blob) } } catch (err) { previewError.value = err.message } finally { previewLoading.value = false } }
function closePreview() { if (previewUrl.value) URL.revokeObjectURL(previewUrl.value); previewFile.value = null; previewUrl.value = '' }
function openShare(file) { shareFile.value = file; shareForm.value = { expiresInHours: 24, maxDownloads: 0 }; shareResult.value = null; shareError.value = ''; shareNotice.value = '' }
function closeShare() { shareFile.value = null }
async function createShare() { shareLoading.value = true; shareError.value = ''; try { const body = await api(`/api/files/${shareFile.value.id}/share`, { method: 'POST', body: JSON.stringify(shareForm.value) }); shareResult.value = body.data; sharedIds.add(shareFile.value.id); localStorage.setItem('filebox_shared_ids', JSON.stringify([...sharedIds])) } catch (err) { shareError.value = err.message } finally { shareLoading.value = false } }
const shareAbsoluteUrl = computed(() => shareResult.value ? new URL(shareResult.value.url, window.location.origin).href : '')
async function copyShare() { try { await navigator.clipboard.writeText(shareAbsoluteUrl.value) } catch { const input = document.querySelector('.share-url input'); input?.select(); document.execCommand('copy') } shareNotice.value = t('files.shareCopied') }
function openSharePage() { window.open(shareAbsoluteUrl.value, '_blank', 'noopener') }
async function revokeShare() { try { await api(`/api/files/${shareFile.value.id}/shares`, { method: 'DELETE' }); sharedIds.delete(shareFile.value.id); localStorage.setItem('filebox_shared_ids', JSON.stringify([...sharedIds])); shareResult.value = null; shareNotice.value = t('files.revokeShares') } catch (err) { shareError.value = err.message } }
function isShared(file) { return sharedIds.has(file.id) }
async function download(file) { try { const response = await fetch(`/api/files/${file.id}/download`, { headers: { Authorization: `Bearer ${localStorage.getItem('filebox_token')}` } }); if (!response.ok) { let body = null; try { body = await response.json() } catch {} throw new Error(localizeError({ status: response.status, data: body?.data, backendMessage: body?.message })) }; const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = file.name; link.click(); URL.revokeObjectURL(link.href) } catch (err) { error.value = err.message } }
async function remove(file) { if (!window.confirm(t('confirm.deleteFile', { name: file.name }))) return; try { await api(`/api/files/${file.id}`, { method: 'DELETE' }); notice.value = t('notice.fileDeleted'); await loadMe(); await loadFiles() } catch (err) { error.value = err.message } }
async function logout() { try { await api('/api/auth/logout', { method: 'POST' }) } finally { clearSession(); router.push('/login') } }
function formatBytes(bytes = 0) { if (bytes < 1024) return `${bytes} B`; const units = ['KB', 'MB', 'GB', 'TB']; let value = bytes; let unit = -1; do { value /= 1024; unit++ } while (value >= 1024 && unit < units.length - 1); return `${value.toFixed(value >= 10 ? 0 : 1)} ${units[unit]}` }
function formatDate(value) { return value ? new Date(value).toLocaleString(currentLocale.value === 'en' ? 'en-US' : currentLocale.value, { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '-' }
function shortMime(value = '') { return value.split('/').pop()?.toUpperCase() || 'FILE' }
onMounted(() => { loadMe(); loadFiles() })
onBeforeUnmount(() => { uploads.value.forEach(item => item.controllers.forEach(controller => controller.abort())); if (previewUrl.value) URL.revokeObjectURL(previewUrl.value) })
</script>
