import { ref } from 'vue'

const supportedLocales = new Set(['zh-CN', 'zh-TW', 'en'])

// The three dictionaries intentionally share one key set so every visible UI state has a translation.
// 三套字典刻意使用同一组键，确保所有可见界面状态都有翻译。
export const zhCN = {
  'lang.zhCN': '简体中文', 'lang.zhTW': '繁體中文', 'lang.en': 'English', 'lang.followSystem': '跟随系统',
  'nav.files': '我的文件', 'nav.admin': '管理后台', 'nav.logs': '日志', 'nav.logout': '退出登录',
  'page.files': '文件库', 'page.admin': '工作区管理', 'page.logs': '操作日志', 'page.login': '登录', 'page.changePassword': '修改密码',
  'common.close': '关闭', 'common.refresh': '刷新', 'common.search': '搜索', 'common.save': '保存', 'common.cancel': '取消', 'common.language': '语言', 'common.loading': '正在加载…', 'common.previous': '上一页', 'common.next': '下一页', 'common.page': '第 {page} 页', 'common.days': '天', 'common.minutes': '分钟', 'common.zeroDisabled': '0 表示关闭', 'common.records': '{count} 条记录', 'common.files': '{count} 个文件', 'common.accounts': '{count} 个账号', 'common.none': '-',
  'login.eyebrow': '欢迎回来', 'login.introEyebrow': 'FILEBOX / 私人存储', 'login.heading': '把文件交给一个清晰、可靠的工作台。', 'login.copy': '集中管理团队文件，保留完整性校验记录，并让每一次下载都可追溯。', 'login.meta': '安全存储 · 分层权限 · 流式传输', 'login.formHeading': '登录到 {title}', 'login.formCopy': '使用你的工作区账号继续。', 'login.username': '用户名', 'login.password': '密码', 'login.remember': '记住本次登录', 'login.submit': '登录', 'login.submitting': '正在登录…', 'login.totpSetupCopy': '请使用验证器扫描二维码，或手动输入密钥后完成绑定。', 'login.totpRequiredCopy': '请输入验证器中的 6 位动态验证码。', 'login.totpQrAlt': 'TOTP 绑定二维码', 'login.totpCode': '动态验证码', 'login.totpSubmit': '验证并继续', 'login.totpBack': '返回登录',
  'password.eyebrow': '安全设置', 'password.heading': '先更新初始密码。', 'password.copy': '为了保护工作区，完成密码更新前暂时无法访问文件和管理功能。', 'password.selfEyebrow': 'ACCOUNT SECURITY', 'password.selfHeading': '修改密码', 'password.selfCopy': '定期更换密码可提升账号安全。', 'password.title': '修改密码', 'password.policy': '密码至少 {passwordMinLength} 位，需满足 {passwordComplexity} 类字符要求（大写、小写、数字、特殊字符）。', 'password.old': '旧密码', 'password.new': '新密码', 'password.confirm': '确认新密码', 'password.submit': '保存新密码', 'password.submitting': '正在保存…', 'password.mismatch': '两次输入的新密码不一致',
  'files.workspaceAdmin': '管理员', 'files.workspaceUser': '用户', 'files.heading': '文件库', 'files.copy': '你的文件都在这里，随时上传、下载或清理。', 'files.quota': '空间使用', 'files.dropTitle': '拖放文件到这里上传', 'files.dropCopy': '单文件直接上传，最大 100MB', 'files.choose': '选择文件', 'files.searchPlaceholder': '搜索文件名', 'files.clearSearch': '清除搜索', 'files.refresh': '刷新列表', 'files.name': '文件名', 'files.size': '大小', 'files.type': '类型', 'files.integrity': '完整性校验', 'files.hashes': 'MD5 / SHA-256', 'files.uploadedAt': '上传时间', 'files.download': '下载文件', 'files.delete': '删除文件', 'files.noMatch': '没有匹配的文件', 'files.noFiles': '文件库还是空的', 'files.noMatchCopy': '换一个关键词试试。', 'files.noFilesCopy': '上传第一个文件，开始建立你的工作区。', 'files.loading': '正在加载文件…', 'files.conflictEyebrow': 'FILE CONFLICT', 'files.conflictHeading': '同名文件已存在', 'files.conflictCopy': '该目录已存在同名文件 {name}，请选择：', 'files.rename': '重命名', 'files.renameHint': '自动加序号', 'files.overwrite': '覆盖', 'files.overwriteHint': '删除旧文件并替换', 'files.uploadPreparing': '准备中', 'files.uploading': '上传中', 'files.checking': '校验中', 'files.completed': '已完成', 'files.uploadCancelled': '已取消上传', 'files.uploadComplete': '{name} 上传完成', 'files.conflictQueue': '还有 {count} 个同名文件待处理', 'files.dismiss': '移除该上传项', 'files.overallRate': '整体速率', 'files.selectAll': '全选', 'files.selectFile': '选择 {name}', 'files.batchDownload': '聚合下载（{count}）', 'files.batchDownloadDone': '已下载 {count} 个文件的压缩包', 'files.tooManyTooLarge': '{count} 个文件超过单文件大小上限 {max}，已跳过', 'files.bulkConfirm': '共 {count} 个文件，确定全部上传吗？',
  'admin.eyebrow': 'ADMINISTRATION / OVERVIEW', 'admin.heading': '工作区管理', 'admin.copy': '管理账号、分配空间，并查看当前存储概况。', 'admin.createUser': '新建用户', 'admin.userCount': '用户数', 'admin.fileCount': '文件数', 'admin.usedSpace': '已用空间', 'admin.diskUsage': '磁盘占用', 'admin.brandEyebrow': 'BRAND SYSTEM', 'admin.brandHeading': '品牌设置', 'admin.brandCopy': '统一管理网站标题、描述、标识与备案信息。', 'admin.siteTitle': '网站标题', 'admin.siteDescription': '网站描述（SEO）', 'admin.icp': 'ICP 备案号', 'admin.police': '公安备案号', 'admin.themeColor': '界面主色', 'admin.resetThemeColor': '恢复默认主色', 'admin.clearField': '清除 {field}', 'admin.favicon': '网页 favicon', 'admin.loginLogo': '登录页 logo', 'admin.mainLogo': '主页 logo', 'admin.removeAsset': '移除自定义资源', 'admin.removeAfterSave': '保存后移除自定义资源', 'admin.customAsset': '已设置自定义资源', 'admin.defaultAsset': '使用内置默认资源', 'admin.saveBrand': '保存品牌设置', 'admin.resetBrand': '恢复默认', 'admin.newAccount': 'NEW ACCOUNT', 'admin.createHeading': '创建用户', 'admin.initialPassword': '初始密码', 'admin.role': '角色', 'admin.userRole': '普通用户', 'admin.adminRole': '管理员', 'admin.quotaGB': '配额（GB）', 'admin.createAccount': '创建账号', 'admin.searchPlaceholder': '搜索用户名', 'admin.refresh': '刷新', 'admin.user': '用户', 'admin.space': '空间使用', 'admin.status': '状态', 'admin.createdAt': '创建时间', 'admin.editUser': '编辑用户', 'admin.deleteUser': '删除用户', 'admin.normal': '正常', 'admin.disabled': '已禁用', 'admin.noUsers': '暂无用户', 'admin.editAccount': 'EDIT ACCOUNT', 'admin.resetPassword': '重置密码', 'admin.passwordUnchanged': '留空则不修改', 'admin.disableAccount': '禁用此账号', 'admin.saveChanges': '保存修改', 'admin.systemLanguage': '系统默认语言', 'admin.systemLanguageCopy': '未设置个人语言的用户将跟随此语言。', 'admin.saveSettings': '保存设置', 'admin.securityEyebrow': 'ACCOUNT SECURITY', 'admin.securityHeading': '安全设置', 'admin.securityCopy': '配置密码强度和来源 IP 登录锁定策略。', 'admin.passwordMinLength': '密码最小长度', 'admin.passwordComplexity': '密码复杂度类别', 'admin.ipLockWindow': 'IP 锁定窗口', 'admin.ipLockThreshold': 'IP 锁定阈值', 'admin.ipAutoUnlock': '自动解锁 IP', 'admin.ipUnlockMinutes': 'IP 解锁时间', 'admin.zeroDisabled': '0 表示关闭', 'admin.totpEnabled': '启用 TOTP 双因素认证', 'admin.ipAclEnabled': '启用 IP 白名单', 'admin.ipWhitelist': 'IP 白名单', 'admin.ipWhitelistPlaceholder': '例如 127.0.0.1, 10.0.0.0/8', 'admin.securitySaveHint': '保存用户后安全设置立即生效。', 'admin.locksEyebrow': 'LOCK MANAGEMENT', 'admin.locksHeading': '锁定管理', 'admin.locksCopy': '查看并解除来源 IP 和用户登录锁定。', 'admin.refreshLocks': '刷新锁定信息', 'admin.ipLocks': 'IP 锁定', 'admin.userLocks': '用户锁定', 'admin.ip': 'IP 地址', 'admin.failedCount': '失败次数', 'admin.lockedUntil': '锁定截止', 'admin.notLocked': '未锁定', 'admin.unlock': '解除', 'admin.noLocks': '暂无锁定记录',
  'logs.eyebrow': 'WORKSPACE / AUDIT LOG', 'logs.heading': '操作日志', 'logs.copy': '查看与你相关的登录、上传和下载记录。', 'logs.searchPlaceholder': '搜索用户、目标或原因', 'logs.actionType': '操作类型', 'logs.allActions': '全部操作', 'logs.result': '结果', 'logs.allResults': '全部结果', 'logs.user': '用户', 'logs.allUsers': '全部用户', 'logs.filter': '筛选', 'logs.refresh': '刷新日志', 'logs.time': '时间', 'logs.target': '目标', 'logs.sourceIP': '来源 IP', 'logs.failureReason': '失败原因', 'logs.success': '成功', 'logs.failure': '失败', 'logs.empty': '暂无日志', 'logs.emptyCopy': '当前筛选条件下没有记录。', 'logs.loading': '正在加载日志…', 'logs.loadingActions': '加载中…', 'logs.login': '登录', 'logs.register': '注册', 'logs.upload': '上传', 'logs.uploadInit': '上传初始化', 'logs.uploadChunk': '上传分片', 'logs.download': '下载', 'logs.share': '创建分享', 'logs.shareView': '查看分享', 'logs.shareDownload': '分享下载',
  'action.save': '保存', 'action.delete': '删除', 'action.download': '下载', 'action.upload': '上传', 'action.search': '搜索', 'action.close': '关闭', 'confirm.deleteFile': '确定删除“{name}”吗？', 'confirm.deleteUser': '确定删除用户“{name}”及其文件吗？', 'confirm.resetBrand': '确定恢复内置品牌并删除全部自定义资源吗？', 'notice.fileDeleted': '文件已删除', 'notice.userCreated': '用户已创建', 'notice.userUpdated': '用户已更新', 'notice.userDeleted': '用户已删除', 'notice.brandSaved': '品牌设置已保存', 'notice.brandReset': '已恢复默认品牌', 'notice.settingsSaved': '设置已保存', 'notice.lockReleased': '锁定已解除',
  'error.requestFailed': '请求失败', 'error.network': '网络连接失败', 'error.invalidResponse': '服务器响应无效', 'error.loginFailed': '用户名或密码错误', 'error.authRequired': '请先登录', 'error.adminRequired': '需要管理员权限', 'error.invalidRequest': '请求格式无效', 'error.invalidLanguage': '语言设置无效', 'error.invalidThemeColor': '主色必须是 #RGB 或 #RRGGBB', 'error.conflict': '同名文件已存在', 'error.userExists': '用户名已存在', 'error.quotaExceeded': '超出用户配额', 'error.quotaExceededDetail': '配额不足：当前已用 {used} / 总配额 {quota}，文件需 {fileSize}，超出 {short}，请清理空间或调整配额', 'error.fileTooLarge': '文件超过单文件大小上限', 'error.fileTooLargeDetail': '文件超过单文件大小上限 {max}', 'error.diskFull': '系统存储空间不足，暂时禁止上传', 'error.fileNotFound': '文件不存在', 'error.fileContentNotFound': '文件内容不存在', 'error.uploadFailed': '上传失败', 'error.downloadFailed': '下载失败', 'error.deleteFailed': '删除文件失败', 'error.passwordTooLong': '密码过长', 'error.invalidSettings': '设置无效', 'error.invalidUser': '用户信息无效', 'error.userNotFound': '用户不存在', 'error.cannotDeleteSelf': '不能删除当前管理员', 'error.brandFailed': '品牌设置失败', 'error.saveLanguage': '保存语言设置失败', 'error.checksumMismatch': '文件校验值不匹配', 'error.invalidFilename': '文件名包含非法字符，禁止上传', 'error.passwordChangeRequired': '请先修改初始密码',
  'logReason.userNotFound': '用户不存在', 'logReason.wrongPassword': '密码错误', 'logReason.userDisabled': '账号已禁用', 'logReason.locked': '账号已锁定', 'logReason.totpFailed': '动态验证码错误', 'logReason.ipLocked': 'IP 已锁定', 'logReason.notFound': '文件不存在', 'logReason.contentNotFound': '文件内容不存在', 'logReason.checksumMismatch': '校验值不匹配', 'logReason.saveFailed': '保存失败', 'logReason.uploadFailed': '上传失败', 'logReason.invalidName': '文件名非法', 'logReason.tooLarge': '超过大小上限', 'logReason.conflict': '同名冲突', 'logReason.diskFull': '磁盘空间不足', 'logReason.quotaExceeded': '超出配额', 'logReason.taskNotFound': '任务不存在', 'logReason.invalidIndex': '分片序号无效', 'logReason.rateLimited': '上传过慢', 'logReason.sizeMismatch': '分片大小不一致', 'logReason.invalidDir': '目录无效', 'logReason.invalidResolve': '冲突处理无效', 'logReason.prepareFailed': '上传空间准备失败', 'logReason.conflictCheckFailed': '同名检查失败', 'logReason.diskCheckFailed': '磁盘检查失败', 'logReason.taskCreateFailed': '任务创建失败', 'logReason.invalidChunkSize': '分片大小非法',
  'title.separator': ' | '
}

export const zhTW = {
  'lang.zhCN': '簡體中文', 'lang.zhTW': '繁體中文', 'lang.en': 'English', 'lang.followSystem': '跟隨系統',
  'nav.files': '我的檔案', 'nav.admin': '管理後台', 'nav.logs': '日誌', 'nav.logout': '登出',
  'page.files': '檔案庫', 'page.admin': '工作區管理', 'page.logs': '操作日誌', 'page.login': '登入', 'page.changePassword': '修改密碼',
  'common.close': '關閉', 'common.refresh': '重新整理', 'common.search': '搜尋', 'common.save': '儲存', 'common.cancel': '取消', 'common.language': '語言', 'common.loading': '正在載入…', 'common.previous': '上一頁', 'common.next': '下一頁', 'common.page': '第 {page} 頁', 'common.days': '天', 'common.minutes': '分鐘', 'common.zeroDisabled': '0 表示關閉', 'common.records': '{count} 筆記錄', 'common.files': '{count} 個檔案', 'common.accounts': '{count} 個帳號', 'common.none': '-',
  'login.eyebrow': '歡迎回來', 'login.introEyebrow': 'FILEBOX / 私人儲存', 'login.heading': '把檔案交給一個清晰、可靠的工作台。', 'login.copy': '集中管理團隊檔案，保留完整性校驗記錄，並讓每一次下載都可追溯。', 'login.meta': '安全儲存 · 分層權限 · 串流傳輸', 'login.formHeading': '登入 {title}', 'login.formCopy': '使用你的工作區帳號繼續。', 'login.username': '使用者名稱', 'login.password': '密碼', 'login.remember': '記住這次登入', 'login.submit': '登入', 'login.submitting': '正在登入…', 'login.totpSetupCopy': '請使用驗證器掃描二維碼，或手動輸入密鑰後完成綁定。', 'login.totpRequiredCopy': '請輸入驗證器中的 6 位動態驗證碼。', 'login.totpQrAlt': 'TOTP 綁定二維碼', 'login.totpCode': '動態驗證碼', 'login.totpSubmit': '驗證並繼續', 'login.totpBack': '返回登入',
  'password.eyebrow': '安全設定', 'password.heading': '先更新初始密碼。', 'password.copy': '為了保護工作區，完成密碼更新前暫時無法存取檔案和管理功能。', 'password.selfEyebrow': 'ACCOUNT SECURITY', 'password.selfHeading': '修改密碼', 'password.selfCopy': '定期更換密碼可提升帳號安全。', 'password.title': '修改密碼', 'password.policy': '密碼至少 {passwordMinLength} 位，需符合 {passwordComplexity} 類字元要求（大寫、小寫、數字、特殊字元）。', 'password.old': '舊密碼', 'password.new': '新密碼', 'password.confirm': '確認新密碼', 'password.submit': '儲存新密碼', 'password.submitting': '正在儲存…', 'password.mismatch': '兩次輸入的新密碼不一致',
  'files.workspaceAdmin': '管理員', 'files.workspaceUser': '使用者', 'files.heading': '檔案庫', 'files.copy': '你的檔案都在這裡，隨時上傳、下載或清理。', 'files.quota': '空間使用量', 'files.dropTitle': '拖放檔案到這裡上傳', 'files.dropCopy': '單檔直接上傳，最大 100MB', 'files.choose': '選擇檔案', 'files.searchPlaceholder': '搜尋檔案名稱', 'files.clearSearch': '清除搜尋', 'files.refresh': '重新整理列表', 'files.name': '檔案名稱', 'files.size': '大小', 'files.type': '類型', 'files.integrity': '完整性校驗', 'files.hashes': 'MD5 / SHA-256', 'files.uploadedAt': '上傳時間', 'files.download': '下載檔案', 'files.delete': '刪除檔案', 'files.noMatch': '沒有符合的檔案', 'files.noFiles': '檔案庫還是空的', 'files.noMatchCopy': '換一個關鍵字試試。', 'files.noFilesCopy': '上傳第一個檔案，開始建立你的工作區。', 'files.loading': '正在載入檔案…', 'files.conflictEyebrow': 'FILE CONFLICT', 'files.conflictHeading': '同名檔案已存在', 'files.conflictCopy': '該目錄已存在同名檔案 {name}，請選擇：', 'files.rename': '重新命名', 'files.renameHint': '自動加上序號', 'files.overwrite': '覆蓋', 'files.overwriteHint': '刪除舊檔案並替換', 'files.uploadPreparing': '準備中', 'files.uploading': '上傳中', 'files.checking': '校驗中', 'files.completed': '已完成', 'files.uploadCancelled': '已取消上傳', 'files.uploadComplete': '{name} 上傳完成', 'files.conflictQueue': '還有 {count} 個同名檔案待處理', 'files.dismiss': '移除該上傳項目', 'files.overallRate': '整體速率', 'files.selectAll': '全選', 'files.selectFile': '選擇 {name}', 'files.batchDownload': '聚合下載（{count}）', 'files.batchDownloadDone': '已下載 {count} 個檔案的壓縮包', 'files.tooManyTooLarge': '{count} 個檔案超過單檔大小上限 {max}，已跳過', 'files.bulkConfirm': '共 {count} 個檔案，確定全部上傳嗎？',
  'admin.eyebrow': 'ADMINISTRATION / OVERVIEW', 'admin.heading': '工作區管理', 'admin.copy': '管理帳號、分配空間，並查看目前儲存概況。', 'admin.createUser': '新增使用者', 'admin.userCount': '使用者數', 'admin.fileCount': '檔案數', 'admin.usedSpace': '已用空間', 'admin.diskUsage': '磁碟使用量', 'admin.brandEyebrow': 'BRAND SYSTEM', 'admin.brandHeading': '品牌設定', 'admin.brandCopy': '統一管理網站標題、描述、標識與備案資訊。', 'admin.siteTitle': '網站標題', 'admin.siteDescription': '網站描述（SEO）', 'admin.icp': 'ICP 備案號', 'admin.police': '公安備案號', 'admin.themeColor': '介面主色', 'admin.resetThemeColor': '恢復預設主色', 'admin.clearField': '清除 {field}', 'admin.favicon': '網站 favicon', 'admin.loginLogo': '登入頁 logo', 'admin.mainLogo': '首頁 logo', 'admin.removeAsset': '移除自訂資源', 'admin.removeAfterSave': '儲存後移除自訂資源', 'admin.customAsset': '已設定自訂資源', 'admin.defaultAsset': '使用內建預設資源', 'admin.saveBrand': '儲存品牌設定', 'admin.resetBrand': '恢復預設', 'admin.newAccount': 'NEW ACCOUNT', 'admin.createHeading': '建立使用者', 'admin.initialPassword': '初始密碼', 'admin.role': '角色', 'admin.userRole': '一般使用者', 'admin.adminRole': '管理員', 'admin.quotaGB': '配額（GB）', 'admin.createAccount': '建立帳號', 'admin.searchPlaceholder': '搜尋使用者名稱', 'admin.refresh': '重新整理', 'admin.user': '使用者', 'admin.space': '空間使用量', 'admin.status': '狀態', 'admin.createdAt': '建立時間', 'admin.editUser': '編輯使用者', 'admin.deleteUser': '刪除使用者', 'admin.normal': '正常', 'admin.disabled': '已停用', 'admin.noUsers': '暫無使用者', 'admin.editAccount': 'EDIT ACCOUNT', 'admin.resetPassword': '重設密碼', 'admin.passwordUnchanged': '留空則不修改', 'admin.disableAccount': '停用此帳號', 'admin.saveChanges': '儲存變更', 'admin.systemLanguage': '系統預設語言', 'admin.systemLanguageCopy': '未設定個人語言的使用者將跟隨此語言。', 'admin.saveSettings': '儲存設定',
  'logs.eyebrow': 'WORKSPACE / AUDIT LOG', 'logs.heading': '操作日誌', 'logs.copy': '查看與你相關的登入、上傳和下載記錄。', 'logs.searchPlaceholder': '搜尋使用者、目標或原因', 'logs.actionType': '操作類型', 'logs.allActions': '全部操作', 'logs.result': '結果', 'logs.allResults': '全部結果', 'logs.user': '使用者', 'logs.allUsers': '全部使用者', 'logs.filter': '篩選', 'logs.refresh': '重新整理日誌', 'logs.time': '時間', 'logs.target': '目標', 'logs.sourceIP': '來源 IP', 'logs.failureReason': '失敗原因', 'logs.success': '成功', 'logs.failure': '失敗', 'logs.empty': '暫無日誌', 'logs.emptyCopy': '目前篩選條件下沒有記錄。', 'logs.loading': '正在載入日誌…', 'logs.loadingActions': '載入中…', 'logs.login': '登入', 'logs.register': '註冊', 'logs.upload': '上傳', 'logs.uploadInit': '上傳初始化', 'logs.uploadChunk': '上傳分片', 'logs.download': '下載', 'logs.share': '建立分享', 'logs.shareView': '查看分享', 'logs.shareDownload': '分享下載',
  'action.save': '儲存', 'action.delete': '刪除', 'action.download': '下載', 'action.upload': '上傳', 'action.search': '搜尋', 'action.close': '關閉', 'confirm.deleteFile': '確定刪除「{name}」嗎？', 'confirm.deleteUser': '確定刪除使用者「{name}」及其檔案嗎？', 'confirm.resetBrand': '確定恢復內建品牌並刪除全部自訂資源嗎？', 'notice.fileDeleted': '檔案已刪除', 'notice.userCreated': '使用者已建立', 'notice.userUpdated': '使用者已更新', 'notice.userDeleted': '使用者已刪除', 'notice.brandSaved': '品牌設定已儲存', 'notice.brandReset': '已恢復預設品牌', 'notice.settingsSaved': '設定已儲存',
  'error.requestFailed': '請求失敗', 'error.network': '網路連線失敗', 'error.invalidResponse': '伺服器回應無效', 'error.loginFailed': '使用者名稱或密碼錯誤', 'error.authRequired': '請先登入', 'error.adminRequired': '需要管理員權限', 'error.invalidRequest': '請求格式無效', 'error.invalidLanguage': '語言設定無效', 'error.invalidThemeColor': '主色必須是 #RGB 或 #RRGGBB', 'error.conflict': '同名檔案已存在', 'error.userExists': '使用者名稱已存在', 'error.quotaExceeded': '超出使用者配額', 'error.quotaExceededDetail': '配額不足：目前已用 {used} / 總配額 {quota}，檔案需 {fileSize}，超出 {short}，請清理空間或調整配額', 'error.fileTooLarge': '檔案超過單檔大小上限', 'error.fileTooLargeDetail': '檔案超過單檔大小上限 {max}', 'error.diskFull': '系統儲存空間不足，暫時禁止上傳', 'error.fileNotFound': '檔案不存在', 'error.fileContentNotFound': '檔案內容不存在', 'error.uploadFailed': '上傳失敗', 'error.downloadFailed': '下載失敗', 'error.deleteFailed': '刪除檔案失敗', 'error.passwordTooLong': '密碼過長', 'error.invalidSettings': '設定無效', 'error.invalidUser': '使用者資訊無效', 'error.userNotFound': '使用者不存在', 'error.cannotDeleteSelf': '不能刪除目前管理員', 'error.brandFailed': '品牌設定失敗', 'error.saveLanguage': '儲存語言設定失敗', 'error.checksumMismatch': '檔案校驗值不符', 'error.invalidFilename': '檔案名稱包含非法字元，禁止上傳',
  'logReason.userNotFound': '使用者不存在', 'logReason.wrongPassword': '密碼錯誤', 'logReason.userDisabled': '帳號已停用', 'logReason.locked': '帳號已鎖定', 'logReason.notFound': '檔案不存在', 'logReason.contentNotFound': '檔案內容不存在', 'logReason.checksumMismatch': '校驗值不符', 'logReason.saveFailed': '儲存失敗', 'logReason.uploadFailed': '上傳失敗', 'logReason.invalidName': '檔名非法', 'logReason.tooLarge': '超過大小上限', 'logReason.conflict': '同名衝突', 'logReason.diskFull': '磁碟空間不足', 'logReason.quotaExceeded': '超出配額', 'logReason.taskNotFound': '任務不存在', 'logReason.invalidIndex': '分片序號無效', 'logReason.rateLimited': '上傳過慢', 'logReason.sizeMismatch': '分片大小不一致', 'logReason.invalidDir': '目錄無效', 'logReason.invalidResolve': '衝突處理無效', 'logReason.prepareFailed': '上傳空間準備失敗', 'logReason.conflictCheckFailed': '同名檢查失敗', 'logReason.diskCheckFailed': '磁碟檢查失敗', 'logReason.taskCreateFailed': '任務建立失敗', 'logReason.invalidChunkSize': '分片大小非法', 'title.separator': ' | '
}

export const en = {
  'lang.zhCN': 'Simplified Chinese', 'lang.zhTW': 'Traditional Chinese', 'lang.en': 'English', 'lang.followSystem': 'Follow system',
  'nav.files': 'My files', 'nav.admin': 'Admin', 'nav.logs': 'Logs', 'nav.logout': 'Log out',
  'page.files': 'File library', 'page.admin': 'Workspace admin', 'page.logs': 'Audit logs', 'page.login': 'Log in',
  'common.close': 'Close', 'common.refresh': 'Refresh', 'common.search': 'Search', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.language': 'Language', 'common.loading': 'Loading…', 'common.previous': 'Previous', 'common.next': 'Next', 'common.page': 'Page {page}', 'common.days': 'days', 'common.records': '{count} records', 'common.files': '{count} files', 'common.accounts': '{count} accounts', 'common.none': '-',
  'login.eyebrow': 'Welcome back', 'login.introEyebrow': 'FILEBOX / PRIVATE STORAGE', 'login.heading': 'Give your files a clear, reliable workspace.', 'login.copy': 'Manage team files in one place, preserve integrity records, and keep every download traceable.', 'login.meta': 'Secure storage · Layered access · Streamed transfer', 'login.formHeading': 'Log in to {title}', 'login.formCopy': 'Continue with your workspace account.', 'login.username': 'Username', 'login.password': 'Password', 'login.remember': 'Remember this login', 'login.submit': 'Log in', 'login.submitting': 'Logging in…',
  'files.workspaceAdmin': 'ADMIN', 'files.workspaceUser': 'USER', 'files.heading': 'File library', 'files.copy': 'Your files are here whenever you need to upload, download, or clean up.', 'files.quota': 'Storage used', 'files.dropTitle': 'Drop files here to upload', 'files.dropCopy': 'Direct single-file upload, up to 100MB', 'files.choose': 'Choose files', 'files.searchPlaceholder': 'Search file names', 'files.clearSearch': 'Clear search', 'files.refresh': 'Refresh file list', 'files.name': 'Name', 'files.size': 'Size', 'files.type': 'Type', 'files.integrity': 'Integrity', 'files.hashes': 'MD5 / SHA-256', 'files.uploadedAt': 'Uploaded', 'files.download': 'Download file', 'files.delete': 'Delete file', 'files.noMatch': 'No matching files', 'files.noFiles': 'Your file library is empty', 'files.noMatchCopy': 'Try another keyword.', 'files.noFilesCopy': 'Upload your first file to start your workspace.', 'files.loading': 'Loading files…', 'files.conflictEyebrow': 'FILE CONFLICT', 'files.conflictHeading': 'A file with this name already exists', 'files.conflictCopy': 'A file named {name} already exists in this directory. Choose an action:', 'files.rename': 'Rename', 'files.renameHint': 'Add a numeric suffix', 'files.overwrite': 'Overwrite', 'files.overwriteHint': 'Delete and replace the old file', 'files.uploadPreparing': 'Preparing', 'files.uploading': 'Uploading', 'files.checking': 'Checking', 'files.completed': 'Completed', 'files.uploadCancelled': 'Upload cancelled', 'files.uploadComplete': '{name} uploaded', 'files.conflictQueue': '{count} more same-name files waiting', 'files.dismiss': 'Dismiss this upload', 'files.overallRate': 'Overall rate', 'files.selectAll': 'Select all', 'files.selectFile': 'Select {name}', 'files.batchDownload': 'Download selected ({count})', 'files.batchDownloadDone': 'Downloaded {count} files as an archive', 'files.tooManyTooLarge': '{count} files exceed the single-file limit of {max} and were skipped', 'files.bulkConfirm': 'Upload all {count} files?',
  'admin.eyebrow': 'ADMINISTRATION / OVERVIEW', 'admin.heading': 'Workspace admin', 'admin.copy': 'Manage accounts, allocate storage, and review current usage.', 'admin.createUser': 'New user', 'admin.userCount': 'Users', 'admin.fileCount': 'Files', 'admin.usedSpace': 'Used space', 'admin.diskUsage': 'Disk usage', 'admin.brandEyebrow': 'BRAND SYSTEM', 'admin.brandHeading': 'Brand settings', 'admin.brandCopy': 'Manage the site title, description, identity, and filing details in one place.', 'admin.siteTitle': 'Site title', 'admin.siteDescription': 'Site description (SEO)', 'admin.icp': 'ICP filing number', 'admin.police': 'Public-security filing number', 'admin.themeColor': 'Interface accent color', 'admin.resetThemeColor': 'Restore default color', 'admin.clearField': 'Clear {field}', 'admin.favicon': 'Site favicon', 'admin.loginLogo': 'Login logo', 'admin.mainLogo': 'Main logo', 'admin.removeAsset': 'Remove custom asset', 'admin.removeAfterSave': 'Custom asset will be removed after saving', 'admin.customAsset': 'Custom asset configured', 'admin.defaultAsset': 'Using built-in default asset', 'admin.saveBrand': 'Save brand settings', 'admin.resetBrand': 'Restore defaults', 'admin.newAccount': 'NEW ACCOUNT', 'admin.createHeading': 'Create user', 'admin.initialPassword': 'Initial password', 'admin.role': 'Role', 'admin.userRole': 'Regular user', 'admin.adminRole': 'Administrator', 'admin.quotaGB': 'Quota (GB)', 'admin.createAccount': 'Create account', 'admin.searchPlaceholder': 'Search usernames', 'admin.refresh': 'Refresh', 'admin.user': 'User', 'admin.space': 'Storage used', 'admin.status': 'Status', 'admin.createdAt': 'Created', 'admin.editUser': 'Edit user', 'admin.deleteUser': 'Delete user', 'admin.normal': 'Active', 'admin.disabled': 'Disabled', 'admin.noUsers': 'No users', 'admin.editAccount': 'EDIT ACCOUNT', 'admin.resetPassword': 'Reset password', 'admin.passwordUnchanged': 'Leave blank to keep unchanged', 'admin.saveChanges': 'Save changes', 'admin.systemLanguage': 'System default language', 'admin.systemLanguageCopy': 'Users without a personal language will follow this setting.', 'admin.saveSettings': 'Save settings',
  'logs.eyebrow': 'WORKSPACE / AUDIT LOG', 'logs.heading': 'Audit logs', 'logs.copy': 'Review login, upload, and download activity related to you.', 'logs.searchPlaceholder': 'Search users, targets, or reasons', 'logs.actionType': 'Action', 'logs.allActions': 'All actions', 'logs.result': 'Result', 'logs.allResults': 'All results', 'logs.user': 'User', 'logs.allUsers': 'All users', 'logs.filter': 'Filter', 'logs.refresh': 'Refresh logs', 'logs.time': 'Time', 'logs.target': 'Target', 'logs.sourceIP': 'Source IP', 'logs.failureReason': 'Failure reason', 'logs.success': 'Success', 'logs.failure': 'Failure', 'logs.empty': 'No logs', 'logs.emptyCopy': 'No records match the current filters.', 'logs.loading': 'Loading logs…', 'logs.loadingActions': 'Loading…', 'logs.login': 'Log in', 'logs.register': 'Register', 'logs.upload': 'Upload', 'logs.uploadInit': 'Upload init', 'logs.uploadChunk': 'Upload chunk', 'logs.download': 'Download', 'logs.share': 'Create share', 'logs.shareView': 'View share', 'logs.shareDownload': 'Download share',
  'action.save': 'Save', 'action.delete': 'Delete', 'action.download': 'Download', 'action.upload': 'Upload', 'action.search': 'Search', 'action.close': 'Close', 'confirm.deleteFile': 'Delete “{name}”?', 'confirm.deleteUser': 'Delete user “{name}” and all of their files?', 'confirm.resetBrand': 'Restore the built-in brand and remove all custom assets?', 'notice.fileDeleted': 'File deleted', 'notice.userCreated': 'User created', 'notice.userUpdated': 'User updated', 'notice.userDeleted': 'User deleted', 'notice.brandSaved': 'Brand settings saved', 'notice.brandReset': 'Default brand restored', 'notice.settingsSaved': 'Settings saved',
  'error.requestFailed': 'Request failed', 'error.network': 'Network connection failed', 'error.invalidResponse': 'Invalid server response', 'error.loginFailed': 'Invalid username or password', 'error.authRequired': 'Please log in first', 'error.adminRequired': 'Administrator permission required', 'error.invalidRequest': 'Invalid request format', 'error.invalidLanguage': 'Invalid language setting', 'error.invalidThemeColor': 'Use #RGB or #RRGGBB', 'error.conflict': 'A file with this name already exists', 'error.userExists': 'Username already exists', 'error.quotaExceeded': 'User quota exceeded', 'error.quotaExceededDetail': 'Quota exceeded: {used} used of {quota}, this file needs {fileSize}, short by {short}. Free up space or adjust the quota', 'error.fileTooLarge': 'File exceeds the single-file size limit', 'error.fileTooLargeDetail': 'File exceeds the single-file size limit of {max}', 'error.diskFull': 'Storage space is insufficient; uploads are temporarily disabled', 'error.fileNotFound': 'File not found', 'error.fileContentNotFound': 'File content not found', 'error.uploadFailed': 'Upload failed', 'error.downloadFailed': 'Download failed', 'error.deleteFailed': 'File deletion failed', 'error.passwordTooLong': 'Password is too long', 'error.invalidSettings': 'Invalid settings', 'error.invalidUser': 'Invalid user information', 'error.userNotFound': 'User not found', 'error.cannotDeleteSelf': 'You cannot delete the current administrator', 'error.brandFailed': 'Brand settings failed', 'error.saveLanguage': 'Could not save language settings', 'error.checksumMismatch': 'File checksum mismatch', 'error.invalidFilename': 'The filename contains invalid characters; upload rejected',
  'logReason.userNotFound': 'User not found', 'logReason.wrongPassword': 'Wrong password', 'logReason.userDisabled': 'Account disabled', 'logReason.locked': 'Account locked', 'logReason.notFound': 'File not found', 'logReason.contentNotFound': 'File content not found', 'logReason.checksumMismatch': 'Checksum mismatch', 'logReason.saveFailed': 'Save failed', 'logReason.uploadFailed': 'Upload failed', 'logReason.invalidName': 'Invalid file name', 'logReason.tooLarge': 'Exceeds the size limit', 'logReason.conflict': 'Name conflict', 'logReason.diskFull': 'Disk space low', 'logReason.quotaExceeded': 'Quota exceeded', 'logReason.taskNotFound': 'Task not found', 'logReason.invalidIndex': 'Invalid chunk index', 'logReason.rateLimited': 'Upload too slow', 'logReason.sizeMismatch': 'Chunk size mismatch', 'logReason.invalidDir': 'Invalid directory', 'logReason.invalidResolve': 'Invalid conflict mode', 'logReason.prepareFailed': 'Could not prepare upload space', 'logReason.conflictCheckFailed': 'Conflict check failed', 'logReason.diskCheckFailed': 'Disk check failed', 'logReason.taskCreateFailed': 'Task creation failed', 'logReason.invalidChunkSize': 'Invalid chunk size', 'title.separator': ' | '
}

Object.assign(zhCN, {
  'files.uploadFolder': '上传文件夹', 'files.instantUpload': '秒传成功', 'files.paused': '已暂停', 'files.resume': '继续', 'files.pause': '暂停', 'files.chunks': '{done}/{total} 分片', 'files.preview': '预览', 'files.share': '分享', 'files.shareDialog': '分享文件', 'files.shareExpiresHours': '有效期（小时）', 'files.shareMaxDownloads': '最大下载次数（0=不限）', 'files.shareUrl': '分享链接', 'files.shareCopied': '链接已复制', 'files.revokeShares': '撤销分享', 'files.shared': '已分享', 'files.openShare': '打开分享页', 'files.retry': '重试', 'files.uploadError': '上传失败', 'files.folderPath': '目录：{path}', 'files.checksum': '校验中 {progress}%', 'files.uploadContinue': '继续上传', 'files.previewUnsupported': '此文件类型不支持在线预览', 'files.previewLoading': '正在加载预览…', 'files.transfers': '传输', 'files.uploads': '上传', 'files.downloads': '下载', 'files.downloading': '下载中', 'files.noTransfers': '暂无传输任务', 'files.showMd5': '显示 MD5', 'files.dropEmpty': '拖拽内容不包含可上传的文件（如空目录），请点击按钮选择文件或文件夹', 'files.root': '根目录', 'files.newFolder': '新建文件夹', 'files.folderName': '文件夹名称', 'files.renameFolder': '重命名文件夹', 'files.deleteFolder': '删除文件夹', 'files.emptyFolder': '此目录为空',
  'share.heading': '文件分享', 'share.download': '下载文件', 'share.expired': '分享链接已过期', 'share.limitReached': '分享次数已用完', 'share.notFound': '分享不存在', 'share.downloads': '已下载 {count} 次', 'share.availableDownloads': '剩余 {count} 次', 'share.expiresAt': '有效期至', 'share.retry': '重试', 'share.backLogin': '返回登录', 'share.loading': '正在读取分享信息…', 'share.owner': '分享者', 'share.preview': '文件预览',
  'login.register': '注册账号', 'login.registerCopy': '还没有账号？立即注册', 'login.registerSubmit': '注册并登录', 'login.confirmPassword': '确认密码', 'login.passwordMismatch': '两次输入的密码不一致', 'login.hasAccount': '已有账号？返回登录', 'login.passwordPolicy': '密码至少 8 位，需包含大写、小写、数字、特殊字符中的至少 3 类。',
  'admin.tabOverview': '概览', 'admin.tabUsers': '用户管理', 'admin.tabSecurity': '安全设置', 'admin.tabBrand': '品牌设置', 'admin.tabLocks': '锁定管理', 'admin.tabSystem': '系统设置', 'admin.logRetentionDays': '日志保存天数', 'admin.logRetentionCopy': '超过周期的日志与归档会在下次写入时自动清理。', 'admin.registerEnabled': '开放注册', 'admin.registerEnabledCopy': '允许未登录用户自助注册普通账号', 'admin.uploadRateLimit': '上传限速（KB/s）', 'admin.uploadRateLimitCopy': '0 表示不限速', 'admin.trustProxy': '信任 X-Forwarded-For', 'admin.trustProxyCopy': '仅在来源地址属于 --trusted-proxies 时使用代理转发的客户端 IP', 'admin.shares': '分享链接', 'admin.shareDownloads': '累计下载',
  'error.registerDisabled': '注册功能未开放', 'error.shareExpired': '分享链接已过期', 'error.shareLimit': '分享次数已用完', 'error.shareNotFound': '分享不存在', 'error.invalidShareHours': '分享有效期无效', 'error.invalidShareMax': '分享次数限制无效', 'error.invalidDir': '目录无效', 'error.invalidChunkSize': '分片大小必须在 2MB-8MB 之间', 'error.invalidRateLimit': '上传限速无效',
  'logReason.shareExpired': '分享已过期', 'logReason.shareLimit': '次数已用完', 'logReason.shareNotFound': '分享不存在',
  'confirm.deleteFolder': '确定删除文件夹“{name}”吗？', 'notice.folderCreated': '文件夹已创建', 'notice.folderRenamed': '文件夹已重命名', 'notice.folderDeleted': '文件夹已删除',
  'nav.changePassword': '修改密码', 'admin.copyright': '版权信息', 'admin.copyrightPlaceholder': 'Copyright © 2026 xxx', 'admin.totpReenroll': '要求下次重新绑定 TOTP', 'admin.totpSecret': 'TOTP 密钥', 'admin.totpSecretCopy': '请立即将此密钥安全地交给用户；关闭窗口后不会再次显示。',
  'logs.systemGroup': '系统配置', 'logs.settingsUpdate': '配置修改', 'logs.brandUpdate': '品牌修改', 'logs.languageUpdate': '语言修改', 'logs.passwordChange': '修改密码', 'logs.passwordReset': '重置密码', 'logs.userCreate': '创建用户', 'logs.userUpdate': '修改用户', 'logs.userDisabled': '禁用用户', 'logs.totpUpdate': 'TOTP 修改', 'logs.ipAclUpdate': 'IP 白名单修改', 'logs.folderCreate': '创建目录', 'logs.folderList': '查看目录', 'logs.folderRename': '重命名目录', 'logs.folderDelete': '删除目录', 'logs.fileList': '查看文件列表', 'logs.adminStats': '查看统计', 'logs.logList': '查看日志'
})
Object.assign(zhTW, {
  'files.uploadFolder': '上傳資料夾', 'files.instantUpload': '秒傳成功', 'files.paused': '已暫停', 'files.resume': '繼續', 'files.pause': '暫停', 'files.chunks': '{done}/{total} 個分片', 'files.preview': '預覽', 'files.share': '分享', 'files.shareDialog': '分享檔案', 'files.shareExpiresHours': '有效期（小時）', 'files.shareMaxDownloads': '最大下載次數（0=不限）', 'files.shareUrl': '分享連結', 'files.shareCopied': '連結已複製', 'files.revokeShares': '撤銷分享', 'files.shared': '已分享', 'files.openShare': '開啟分享頁', 'files.retry': '重試', 'files.uploadError': '上傳失敗', 'files.folderPath': '目錄：{path}', 'files.checksum': '校驗中 {progress}%', 'files.uploadContinue': '繼續上傳', 'files.previewUnsupported': '此檔案類型不支援線上預覽', 'files.previewLoading': '正在載入預覽…', 'files.transfers': '傳輸', 'files.uploads': '上傳', 'files.downloads': '下載', 'files.downloading': '下載中', 'files.noTransfers': '暫無傳輸任務', 'files.showMd5': '顯示 MD5', 'files.dropEmpty': '拖曳內容不包含可上傳的檔案（如空目錄），請點按鈕選擇檔案或資料夾', 'files.root': '根目錄', 'files.newFolder': '新增資料夾', 'files.folderName': '資料夾名稱', 'files.renameFolder': '重新命名資料夾', 'files.deleteFolder': '刪除資料夾', 'files.emptyFolder': '此目錄為空',
  'share.heading': '檔案分享', 'share.download': '下載檔案', 'share.expired': '分享連結已過期', 'share.limitReached': '分享次數已用完', 'share.notFound': '分享不存在', 'share.downloads': '已下載 {count} 次', 'share.availableDownloads': '剩餘 {count} 次', 'share.expiresAt': '有效期至', 'share.retry': '重試', 'share.backLogin': '返回登入', 'share.loading': '正在讀取分享資訊…', 'share.owner': '分享者', 'share.preview': '檔案預覽',
  'login.register': '註冊帳號', 'login.registerCopy': '還沒有帳號？立即註冊', 'login.registerSubmit': '註冊並登入', 'login.confirmPassword': '確認密碼', 'login.passwordMismatch': '兩次輸入的密碼不一致', 'login.hasAccount': '已有帳號？返回登入', 'login.passwordPolicy': '密碼至少 8 位，需包含大寫、小寫、數字、特殊字元中的至少 3 類。',
  'admin.tabOverview': '概覽', 'admin.tabUsers': '使用者管理', 'admin.tabSecurity': '安全設定', 'admin.tabBrand': '品牌設定', 'admin.tabLocks': '鎖定管理', 'admin.tabSystem': '系統設定', 'admin.logRetentionDays': '日誌保留天數', 'admin.logRetentionCopy': '超過週期的日誌與封存會在下次寫入時自動清理。', 'admin.registerEnabled': '開放註冊', 'admin.registerEnabledCopy': '允許未登入使用者自行註冊一般帳號', 'admin.uploadRateLimit': '上傳限速（KB/s）', 'admin.uploadRateLimitCopy': '0 表示不限速', 'admin.trustProxy': '信任 X-Forwarded-For', 'admin.trustProxyCopy': '僅在來源位址屬於 --trusted-proxies 時使用代理轉送的用戶端 IP', 'admin.shares': '分享連結', 'admin.shareDownloads': '累計下載',
  'error.registerDisabled': '註冊功能未開放', 'error.shareExpired': '分享連結已過期', 'error.shareLimit': '分享次數已用完', 'error.shareNotFound': '分享不存在', 'error.invalidShareHours': '分享有效期無效', 'error.invalidShareMax': '分享次數限制無效', 'error.invalidDir': '目錄無效', 'error.invalidChunkSize': '分片大小必須在 2MB-8MB 之間', 'error.invalidRateLimit': '上傳限速無效',
  'logReason.shareExpired': '分享已過期', 'logReason.shareLimit': '次數已用完', 'logReason.shareNotFound': '分享不存在',
  'confirm.deleteFolder': '確定刪除資料夾「{name}」嗎？', 'notice.folderCreated': '資料夾已建立', 'notice.folderRenamed': '資料夾已重新命名', 'notice.folderDeleted': '資料夾已刪除',
  'nav.changePassword': '修改密碼', 'admin.copyright': '版權資訊', 'admin.copyrightPlaceholder': 'Copyright © 2026 xxx', 'admin.totpReenroll': '要求下次重新綁定 TOTP', 'admin.totpSecret': 'TOTP 密鑰', 'admin.totpSecretCopy': '請立即將此密鑰安全地交給使用者；關閉視窗後不會再次顯示。',
  'logs.systemGroup': '系統設定', 'logs.settingsUpdate': '設定修改', 'logs.brandUpdate': '品牌修改', 'logs.languageUpdate': '語言修改', 'logs.passwordChange': '修改密碼', 'logs.passwordReset': '重設密碼', 'logs.userCreate': '建立使用者', 'logs.userUpdate': '修改使用者', 'logs.userDisabled': '停用使用者', 'logs.totpUpdate': 'TOTP 修改', 'logs.ipAclUpdate': 'IP 白名單修改', 'logs.folderCreate': '建立資料夾', 'logs.folderList': '檢視資料夾', 'logs.folderRename': '重新命名資料夾', 'logs.folderDelete': '刪除資料夾', 'logs.fileList': '檢視檔案列表', 'logs.adminStats': '檢視統計', 'logs.logList': '檢視日誌'
})
Object.assign(en, {
  'files.uploadFolder': 'Upload folder', 'files.instantUpload': 'Instant upload complete', 'files.paused': 'Paused', 'files.resume': 'Resume', 'files.pause': 'Pause', 'files.chunks': '{done}/{total} chunks', 'files.preview': 'Preview', 'files.share': 'Share', 'files.shareDialog': 'Share file', 'files.shareExpiresHours': 'Validity (hours)', 'files.shareMaxDownloads': 'Maximum downloads (0 = unlimited)', 'files.shareUrl': 'Share link', 'files.shareCopied': 'Link copied', 'files.revokeShares': 'Revoke shares', 'files.shared': 'Shared', 'files.openShare': 'Open share page', 'files.retry': 'Retry', 'files.uploadError': 'Upload failed', 'files.folderPath': 'Folder: {path}', 'files.checksum': 'Checking {progress}%', 'files.uploadContinue': 'Continue upload', 'files.previewUnsupported': 'This file type cannot be previewed online', 'files.previewLoading': 'Loading preview…', 'files.transfers': 'Transfers', 'files.uploads': 'Uploads', 'files.downloads': 'Downloads', 'files.downloading': 'Downloading', 'files.noTransfers': 'No active transfers', 'files.showMd5': 'Show MD5', 'files.dropEmpty': 'The dropped content contains no uploadable files (for example an empty folder). Use the buttons to choose files or a folder.', 'files.root': 'Root', 'files.newFolder': 'New folder', 'files.folderName': 'Folder name', 'files.renameFolder': 'Rename folder', 'files.deleteFolder': 'Delete folder', 'files.emptyFolder': 'This folder is empty',
  'share.heading': 'File share', 'share.download': 'Download file', 'share.expired': 'This share link has expired', 'share.limitReached': 'The share download limit has been reached', 'share.notFound': 'Share not found', 'share.downloads': 'Downloaded {count} times', 'share.availableDownloads': '{count} downloads remaining', 'share.expiresAt': 'Expires at', 'share.retry': 'Retry', 'share.backLogin': 'Back to login', 'share.loading': 'Loading share information…', 'share.owner': 'Shared by', 'share.preview': 'File preview',
  'login.register': 'Register account', 'login.registerCopy': 'No account yet? Register now', 'login.registerSubmit': 'Register and log in', 'login.confirmPassword': 'Confirm password', 'login.passwordMismatch': 'The passwords do not match', 'login.hasAccount': 'Already have an account? Back to login', 'login.passwordPolicy': 'Use at least 8 characters and 3 of uppercase, lowercase, number, and special characters.',
  'admin.tabOverview': 'Overview', 'admin.tabUsers': 'Users', 'admin.tabSecurity': 'Security', 'admin.tabBrand': 'Branding', 'admin.tabLocks': 'Locks', 'admin.tabSystem': 'System', 'admin.logRetentionDays': 'Log retention days', 'admin.logRetentionCopy': 'Logs and archives older than the retention period are cleaned on the next write.', 'admin.registerEnabled': 'Open registration', 'admin.registerEnabledCopy': 'Allow visitors to register regular accounts', 'admin.uploadRateLimit': 'Upload rate limit (KB/s)', 'admin.uploadRateLimitCopy': '0 means unlimited', 'admin.trustProxy': 'Trust X-Forwarded-For', 'admin.trustProxyCopy': 'Use the forwarded client IP only when the source is in --trusted-proxies', 'admin.shares': 'Share links', 'admin.shareDownloads': 'Total downloads',
  'error.registerDisabled': 'Registration is not open', 'error.shareExpired': 'Share link has expired', 'error.shareLimit': 'Share download limit reached', 'error.shareNotFound': 'Share not found', 'error.invalidShareHours': 'Invalid share validity period', 'error.invalidShareMax': 'Invalid share download limit', 'error.invalidDir': 'Invalid directory', 'error.invalidChunkSize': 'Chunk size must be between 2MB and 8MB', 'error.invalidRateLimit': 'Invalid upload rate limit',
  'logReason.shareExpired': 'Share expired', 'logReason.shareLimit': 'Download limit reached', 'logReason.shareNotFound': 'Share not found',
  'confirm.deleteFolder': 'Delete folder “{name}”?', 'notice.folderCreated': 'Folder created', 'notice.folderRenamed': 'Folder renamed', 'notice.folderDeleted': 'Folder deleted',
  'nav.changePassword': 'Change password', 'admin.copyright': 'Copyright', 'admin.copyrightPlaceholder': 'Copyright © 2026 xxx', 'admin.totpReenroll': 'Require TOTP re-enrollment', 'admin.totpSecret': 'TOTP secret', 'admin.totpSecretCopy': 'Give this secret to the user securely now; it will not be shown again after closing this window.',
  'logs.systemGroup': 'System configuration', 'logs.settingsUpdate': 'Settings update', 'logs.brandUpdate': 'Branding update', 'logs.languageUpdate': 'Language update', 'logs.passwordChange': 'Password change', 'logs.passwordReset': 'Password reset', 'logs.userCreate': 'User created', 'logs.userUpdate': 'User updated', 'logs.userDisabled': 'User disabled', 'logs.totpUpdate': 'TOTP update', 'logs.ipAclUpdate': 'IP allowlist update', 'logs.folderCreate': 'Folder created', 'logs.folderList': 'Folder list', 'logs.folderRename': 'Folder renamed', 'logs.folderDelete': 'Folder deleted', 'logs.fileList': 'File list', 'logs.adminStats': 'Stats view', 'logs.logList': 'Log list'
})

Object.assign(zhCN, {
	'error.invalidLogRetentionDays': '日志留存天数无效', 'error.invalidLockThreshold': '登录失败锁定阈值无效', 'error.invalidAutoUnlockMinutes': '自动解锁时长无效', 'error.invalidDefaultLang': '系统默认语言无效', 'error.invalidPasswordMinLength': '密码最小长度无效', 'error.invalidPasswordComplexity': '密码复杂度无效', 'error.invalidIPLockWindow': 'IP 锁定窗口无效', 'error.invalidIPLockThreshold': 'IP 锁定阈值无效', 'error.invalidIPUnlockMinutes': 'IP 解锁时长无效',
  'page.changePassword': '修改密码', 'common.minutes': '分钟', 'common.zeroDisabled': '0 表示关闭',
  'login.totpSetupCopy': '请使用验证器扫描二维码，或手动输入密钥后完成绑定。', 'login.totpRequiredCopy': '请输入验证器中的 6 位动态验证码。', 'login.totpQrAlt': 'TOTP 绑定二维码', 'login.totpCode': '动态验证码', 'login.totpSubmit': '验证并继续', 'login.totpBack': '返回登录',
  'password.eyebrow': '安全设置', 'password.heading': '先更新初始密码。', 'password.copy': '为了保护工作区，完成密码更新前暂时无法访问文件和管理功能。', 'password.selfEyebrow': 'ACCOUNT SECURITY', 'password.selfHeading': '修改密码', 'password.selfCopy': '定期更换密码可提升账号安全。', 'password.title': '修改密码', 'password.policy': '密码至少 {passwordMinLength} 位，需满足 {passwordComplexity} 类字符要求（大写、小写、数字、特殊字符）。', 'password.old': '旧密码', 'password.new': '新密码', 'password.confirm': '确认新密码', 'password.submit': '保存新密码', 'password.submitting': '正在保存…', 'password.mismatch': '两次输入的新密码不一致',
  'admin.securityEyebrow': 'ACCOUNT SECURITY', 'admin.securityHeading': '安全设置', 'admin.securityCopy': '配置密码强度和来源 IP 登录锁定策略。', 'admin.passwordMinLength': '密码最小长度', 'admin.passwordComplexity': '密码复杂度类别', 'admin.ipLockWindow': 'IP 锁定窗口', 'admin.ipLockThreshold': 'IP 锁定阈值', 'admin.ipAutoUnlock': '自动解锁 IP', 'admin.ipUnlockMinutes': 'IP 解锁时间', 'admin.totpEnabled': '启用 TOTP 双因素认证', 'admin.ipAclEnabled': '启用 IP 白名单', 'admin.ipWhitelist': 'IP 白名单', 'admin.ipWhitelistPlaceholder': '例如 127.0.0.1, 10.0.0.0/8', 'admin.securitySaveHint': '保存用户后安全设置立即生效。', 'admin.locksEyebrow': 'LOCK MANAGEMENT', 'admin.locksHeading': '锁定管理', 'admin.locksCopy': '查看并解除来源 IP 和用户登录锁定。', 'admin.refreshLocks': '刷新锁定信息', 'admin.ipLocks': 'IP 锁定', 'admin.userLocks': '用户锁定', 'admin.ip': 'IP 地址', 'admin.failedCount': '失败次数', 'admin.lockedUntil': '锁定截止', 'admin.notLocked': '未锁定', 'admin.unlock': '解除', 'admin.noLocks': '暂无锁定记录', 'notice.lockReleased': '锁定已解除', 'error.passwordChangeRequired': '请先修改初始密码', 'logReason.totpFailed': '动态验证码错误', 'logReason.ipLocked': 'IP 已锁定'
})
Object.assign(zhTW, {
	'error.invalidLogRetentionDays': '日誌保留天數無效', 'error.invalidLockThreshold': '登入失敗鎖定閾值無效', 'error.invalidAutoUnlockMinutes': '自動解除時間無效', 'error.invalidDefaultLang': '系統預設語言無效', 'error.invalidPasswordMinLength': '密碼最小長度無效', 'error.invalidPasswordComplexity': '密碼複雜度無效', 'error.invalidIPLockWindow': 'IP 鎖定視窗無效', 'error.invalidIPLockThreshold': 'IP 鎖定閾值無效', 'error.invalidIPUnlockMinutes': 'IP 解除時間無效',
  'page.changePassword': '修改密碼', 'common.minutes': '分鐘', 'common.zeroDisabled': '0 表示關閉',
  'login.totpSetupCopy': '請使用驗證器掃描二維碼，或手動輸入密鑰後完成綁定。', 'login.totpRequiredCopy': '請輸入驗證器中的 6 位動態驗證碼。', 'login.totpQrAlt': 'TOTP 綁定二維碼', 'login.totpCode': '動態驗證碼', 'login.totpSubmit': '驗證並繼續', 'login.totpBack': '返回登入',
  'password.eyebrow': '安全設定', 'password.heading': '先更新初始密碼。', 'password.copy': '為了保護工作區，完成密碼更新前暫時無法存取檔案和管理功能。', 'password.selfEyebrow': 'ACCOUNT SECURITY', 'password.selfHeading': '修改密碼', 'password.selfCopy': '定期更換密碼可提升帳號安全。', 'password.title': '修改密碼', 'password.policy': '密碼至少 {passwordMinLength} 位，需符合 {passwordComplexity} 類字元要求（大寫、小寫、數字、特殊字元）。', 'password.old': '舊密碼', 'password.new': '新密碼', 'password.confirm': '確認新密碼', 'password.submit': '儲存新密碼', 'password.submitting': '正在儲存…', 'password.mismatch': '兩次輸入的新密碼不一致',
  'admin.securityEyebrow': 'ACCOUNT SECURITY', 'admin.securityHeading': '安全設定', 'admin.securityCopy': '設定密碼強度和來源 IP 登入鎖定策略。', 'admin.passwordMinLength': '密碼最小長度', 'admin.passwordComplexity': '密碼複雜度類別', 'admin.ipLockWindow': 'IP 鎖定視窗', 'admin.ipLockThreshold': 'IP 鎖定閾值', 'admin.ipAutoUnlock': '自動解除 IP', 'admin.ipUnlockMinutes': 'IP 解除時間', 'admin.totpEnabled': '啟用 TOTP 雙因素驗證', 'admin.ipAclEnabled': '啟用 IP 白名單', 'admin.ipWhitelist': 'IP 白名單', 'admin.ipWhitelistPlaceholder': '例如 127.0.0.1, 10.0.0.0/8', 'admin.securitySaveHint': '儲存使用者後安全設定立即生效。', 'admin.locksEyebrow': 'LOCK MANAGEMENT', 'admin.locksHeading': '鎖定管理', 'admin.locksCopy': '查看並解除來源 IP 和使用者登入鎖定。', 'admin.refreshLocks': '重新整理鎖定資訊', 'admin.ipLocks': 'IP 鎖定', 'admin.userLocks': '使用者鎖定', 'admin.ip': 'IP 位址', 'admin.failedCount': '失敗次數', 'admin.lockedUntil': '鎖定截止', 'admin.notLocked': '未鎖定', 'admin.unlock': '解除', 'admin.noLocks': '暫無鎖定記錄', 'notice.lockReleased': '鎖定已解除', 'error.passwordChangeRequired': '請先修改初始密碼', 'logReason.totpFailed': '動態驗證碼錯誤', 'logReason.ipLocked': 'IP 已鎖定'
})
Object.assign(en, {
	'error.invalidLogRetentionDays': 'Invalid log retention days', 'error.invalidLockThreshold': 'Invalid failed-login lock threshold', 'error.invalidAutoUnlockMinutes': 'Invalid auto-unlock period', 'error.invalidDefaultLang': 'Invalid system default language', 'error.invalidPasswordMinLength': 'Invalid minimum password length', 'error.invalidPasswordComplexity': 'Invalid password complexity', 'error.invalidIPLockWindow': 'Invalid IP lock window', 'error.invalidIPLockThreshold': 'Invalid IP lock threshold', 'error.invalidIPUnlockMinutes': 'Invalid IP unlock period',
  'page.changePassword': 'Change password', 'common.minutes': 'minutes', 'common.zeroDisabled': '0 disables this setting',
  'login.totpSetupCopy': 'Scan the QR code with an authenticator, or enter the secret manually to bind this account.', 'login.totpRequiredCopy': 'Enter the 6-digit code from your authenticator.', 'login.totpQrAlt': 'TOTP binding QR code', 'login.totpCode': 'Authenticator code', 'login.totpSubmit': 'Verify and continue', 'login.totpBack': 'Back to login',
  'password.eyebrow': 'SECURITY SETTINGS', 'password.heading': 'Update the initial password first.', 'password.copy': 'File and admin features remain locked until the password is updated.', 'password.selfEyebrow': 'ACCOUNT SECURITY', 'password.selfHeading': 'Change password', 'password.selfCopy': 'Rotating your password regularly improves account security.', 'password.title': 'Change password', 'password.policy': 'Use at least {passwordMinLength} characters and {passwordComplexity} character classes (upper, lower, number, special).', 'password.old': 'Current password', 'password.new': 'New password', 'password.confirm': 'Confirm new password', 'password.submit': 'Save new password', 'password.submitting': 'Saving…', 'password.mismatch': 'The new passwords do not match',
  'admin.securityEyebrow': 'ACCOUNT SECURITY', 'admin.securityHeading': 'Security settings', 'admin.securityCopy': 'Configure password strength and source-IP login lock policies.', 'admin.passwordMinLength': 'Minimum password length', 'admin.passwordComplexity': 'Password complexity classes', 'admin.ipLockWindow': 'IP lock window', 'admin.ipLockThreshold': 'IP lock threshold', 'admin.ipAutoUnlock': 'Auto-unlock IPs', 'admin.ipUnlockMinutes': 'IP unlock period', 'admin.totpEnabled': 'Enable TOTP two-factor authentication', 'admin.ipAclEnabled': 'Enable IP allowlist', 'admin.ipWhitelist': 'IP allowlist', 'admin.ipWhitelistPlaceholder': 'For example 127.0.0.1, 10.0.0.0/8', 'admin.securitySaveHint': 'Security changes take effect after saving the user.', 'admin.locksEyebrow': 'LOCK MANAGEMENT', 'admin.locksHeading': 'Lock management', 'admin.locksCopy': 'Review and release source-IP and user login locks.', 'admin.refreshLocks': 'Refresh locks', 'admin.ipLocks': 'IP locks', 'admin.userLocks': 'User locks', 'admin.ip': 'IP address', 'admin.failedCount': 'Failures', 'admin.lockedUntil': 'Locked until', 'admin.notLocked': 'Not locked', 'admin.unlock': 'Release', 'admin.noLocks': 'No lock records', 'notice.lockReleased': 'Lock released', 'error.passwordChangeRequired': 'Change the initial password first', 'logReason.totpFailed': 'Invalid authenticator code', 'logReason.ipLocked': 'IP locked'
})

Object.assign(zhCN, {
  'files.batchDelete': '删除所选（{count}）', 'confirm.deleteFiles': '确定删除选中的 {count} 个文件吗？', 'notice.filesDeleted': '已删除 {count} 个文件', 'admin.folderCount': '目录数', 'error.batchDeleteEmpty': '请至少选择一个文件', 'error.invalidFileId': '文件编号无效', 'logs.delete': '删除文件'
})
Object.assign(zhTW, {
  'files.batchDelete': '刪除所選（{count}）', 'confirm.deleteFiles': '確定刪除選取的 {count} 個檔案嗎？', 'notice.filesDeleted': '已刪除 {count} 個檔案', 'admin.folderCount': '目錄數', 'error.batchDeleteEmpty': '請至少選擇一個檔案', 'error.invalidFileId': '檔案編號無效', 'logs.delete': '刪除檔案'
})
Object.assign(en, {
  'files.batchDelete': 'Delete selected ({count})', 'confirm.deleteFiles': 'Delete the selected {count} files?', 'notice.filesDeleted': '{count} files deleted', 'admin.folderCount': 'Folders', 'error.batchDeleteEmpty': 'Select at least one file', 'error.invalidFileId': 'Invalid file id', 'logs.delete': 'Delete file'
})

Object.assign(zhCN, {
  'collection.upload': '上传收集', 'collection.create': '创建上传收集', 'collection.my': '我的收集', 'collection.createTitle': '生成上传收集链接', 'collection.name': '名称', 'collection.expiresInHours': '有效期（小时）', 'collection.maxUploads': '上传次数上限（0=不限）', 'collection.maxFileBytesMB': '单文件大小上限（MB，0=不限）', 'collection.link': '收集链接', 'collection.copy': '复制链接', 'collection.copied': '链接已复制', 'collection.status': '状态', 'collection.uploadCount': '已收次数', 'collection.remaining': '剩余时间', 'collection.active': '可上传', 'collection.expired': '收集链接已过期', 'collection.revoked': '收集链接已撤销', 'collection.limitReached': '收集链接上传次数已用完', 'collection.fileTooLarge': '文件超过收集链接单文件大小上限', 'collection.uploadCopy': '可选择多个文件，文件会直接进入创建者的文件库', 'collection.choose': '选择文件', 'collection.drop': '拖放文件到这里', 'collection.remark': '备注', 'collection.remarkPlaceholder': '可选，填写给文件接收者的备注', 'collection.pending': '等待上传', 'collection.checksum': '校验中', 'collection.uploading': '上传中', 'collection.checking': '校验中', 'collection.completed': '已完成', 'collection.instant': '秒传成功', 'collection.allCompleted': '文件已全部上传', 'collection.uploadedFiles': '已上传文件', 'collection.originalName': '原始文件名', 'collection.receivedAt': '收到时间', 'collection.unlimited': '不限', 'collection.viewFiles': '查看已收文件', 'collection.revoke': '撤销', 'collection.noCollections': '暂无上传收集链接', 'collection.files': '已收文件', 'collection.confirmRevoke': '确定撤销这个上传收集链接吗？', 'collection.createFailed': '创建收集链接失败'
})
Object.assign(zhTW, {
  'collection.upload': '上傳收集', 'collection.create': '建立上傳收集', 'collection.my': '我的收集', 'collection.createTitle': '產生上傳收集連結', 'collection.name': '名稱', 'collection.expiresInHours': '有效期（小時）', 'collection.maxUploads': '上傳次數上限（0=不限）', 'collection.maxFileBytesMB': '單檔大小上限（MB，0=不限）', 'collection.link': '收集連結', 'collection.copy': '複製連結', 'collection.copied': '連結已複製', 'collection.status': '狀態', 'collection.uploadCount': '已收次數', 'collection.remaining': '剩餘時間', 'collection.active': '可上傳', 'collection.expired': '收集連結已過期', 'collection.revoked': '收集連結已撤銷', 'collection.limitReached': '收集連結上傳次數已用完', 'collection.fileTooLarge': '檔案超過收集連結單檔大小上限', 'collection.uploadCopy': '可選擇多個檔案，檔案會直接進入建立者的檔案庫', 'collection.choose': '選擇檔案', 'collection.drop': '拖曳檔案到這裡', 'collection.remark': '備註', 'collection.remarkPlaceholder': '選填，填寫給檔案接收者的備註', 'collection.pending': '等待上傳', 'collection.checksum': '校驗中', 'collection.uploading': '上傳中', 'collection.checking': '校驗中', 'collection.completed': '已完成', 'collection.instant': '秒傳成功', 'collection.allCompleted': '檔案已全部上傳', 'collection.uploadedFiles': '已上傳檔案', 'collection.originalName': '原始檔名', 'collection.receivedAt': '收到時間', 'collection.remaining': '剩餘時間', 'collection.unlimited': '不限', 'collection.viewFiles': '查看已收檔案', 'collection.revoke': '撤銷', 'collection.noCollections': '暫無上傳收集連結', 'collection.files': '已收檔案', 'collection.confirmRevoke': '確定撤銷這個上傳收集連結嗎？', 'collection.createFailed': '建立收集連結失敗'
})
Object.assign(en, {
  'collection.upload': 'Upload collection', 'collection.create': 'Create upload collection', 'collection.my': 'My collections', 'collection.createTitle': 'Generate upload collection link', 'collection.name': 'Name', 'collection.expiresInHours': 'Validity (hours)', 'collection.maxUploads': 'Upload limit (0 = unlimited)', 'collection.maxFileBytesMB': 'Single-file limit (MB, 0 = unlimited)', 'collection.link': 'Collection link', 'collection.copy': 'Copy link', 'collection.copied': 'Link copied', 'collection.status': 'Status', 'collection.uploadCount': 'Received', 'collection.remaining': 'Time remaining', 'collection.active': 'Available', 'collection.expired': 'Collection expired', 'collection.revoked': 'Collection revoked', 'collection.limitReached': 'Upload limit reached', 'collection.fileTooLarge': 'File exceeds the collection file-size limit', 'collection.uploadCopy': 'Choose multiple files to send them directly to the owner\'s file library', 'collection.choose': 'Choose files', 'collection.drop': 'Drop files here', 'collection.remark': 'Remark', 'collection.remarkPlaceholder': 'Optional note for the recipient', 'collection.pending': 'Waiting', 'collection.checksum': 'Checking', 'collection.uploading': 'Uploading', 'collection.checking': 'Verifying', 'collection.completed': 'Completed', 'collection.instant': 'Instant upload complete', 'collection.allCompleted': 'All files uploaded', 'collection.uploadedFiles': 'Uploaded files', 'collection.originalName': 'Original name', 'collection.receivedAt': 'Received', 'collection.unlimited': 'Unlimited', 'collection.viewFiles': 'View received files', 'collection.revoke': 'Revoke', 'collection.noCollections': 'No upload collections yet', 'collection.files': 'Received files', 'collection.confirmRevoke': 'Revoke this upload collection?', 'collection.createFailed': 'Could not create upload collection'
})
Object.assign(zhCN, { 'logs.collection': '上传收集', 'logs.uploadCollect': '外部上传成功', 'logs.uploadCollectFail': '外部上传失败' })
Object.assign(zhTW, { 'logs.collection': '上傳收集', 'logs.uploadCollect': '外部上傳成功', 'logs.uploadCollectFail': '外部上傳失敗' })
Object.assign(en, { 'logs.collection': 'Upload collection', 'logs.uploadCollect': 'External upload', 'logs.uploadCollectFail': 'External upload failed' })

Object.assign(zhCN, { 'collection.expiresAt': '有效期至', 'collection.maxFileBytes': '单文件大小上限' })
Object.assign(zhTW, { 'collection.expiresAt': '有效期至', 'collection.maxFileBytes': '單檔大小上限' })
Object.assign(en, { 'collection.expiresAt': 'Expires at', 'collection.maxFileBytes': 'Single-file limit' })
Object.assign(zhTW, { 'admin.disableAccount': '停用此帳號', 'admin.zeroDisabled': '0 表示關閉' })
Object.assign(en, { 'admin.disableAccount': 'Disable this account', 'admin.zeroDisabled': '0 disables this setting' })

// readOnly keys are kept identical across all three locale dictionaries.
// readOnly 键集在三种语言中保持一致，避免管理端和文件页出现未翻译状态。
Object.assign(zhCN, { 'readOnly.label': '只读时段', 'readOnly.from': '开始时间', 'readOnly.until': '结束时间', 'readOnly.clear': '清除时间', 'readOnly.notice': '当前账号处于只读时段，仅可查看和下载', 'readOnly.error': '当前账号处于只读时段，仅可查看和下载', 'readOnly.invalidWindow': '只读时段无效：请同时填写合法的开始和结束时间' })
Object.assign(zhTW, { 'readOnly.label': '唯讀時段', 'readOnly.from': '開始時間', 'readOnly.until': '結束時間', 'readOnly.clear': '清除時間', 'readOnly.notice': '目前帳號處於唯讀時段，僅可查看和下載', 'readOnly.error': '目前帳號處於唯讀時段，僅可查看和下載', 'readOnly.invalidWindow': '唯讀時段無效：請同時填寫合法的開始和結束時間' })
Object.assign(en, { 'readOnly.label': 'Read-only window', 'readOnly.from': 'Start time', 'readOnly.until': 'End time', 'readOnly.clear': 'Clear time', 'readOnly.notice': 'This account is in a read-only window. Only viewing and downloading are allowed.', 'readOnly.error': 'This account is in a read-only window. Only viewing and downloading are allowed.', 'readOnly.invalidWindow': 'Invalid read-only window: enter both a valid start and end time.' })

export const dictionaries = { 'zh-CN': zhCN, 'zh-TW': zhTW, en }
export const currentLocale = ref('zh-CN')
export const systemLocale = ref('zh-CN')

function validLocale(value) { return supportedLocales.has(value) }

// setLocale updates the reactive locale and persists only explicit language choices.
// setLocale 更新响应式语言，并仅持久化明确选择的语言。
export function setLocale(lang) {
  const next = lang === '' ? systemLocale.value : lang
  currentLocale.value = validLocale(next) ? next : 'zh-CN'
  document.documentElement.lang = currentLocale.value
  if (lang === '') localStorage.removeItem('filebox_locale')
  else if (validLocale(lang)) localStorage.setItem('filebox_locale', lang)
}

export function t(key, params = {}) {
  const dictionary = dictionaries[currentLocale.value] || zhCN
  let value = dictionary[key] ?? zhCN[key] ?? key
  return String(value).replace(/\{(\w+)\}/g, (_, name) => params[name] ?? `{${name}}`)
}

// loadLocale resolves explicit local preference, authenticated user preference, public system default, then zh-CN.
// loadLocale 按本地明确选择、登录用户偏好、公开系统默认、简体中文的顺序解析语言。
export async function loadLocale(defaultLang = '') {
  const saved = localStorage.getItem('filebox_locale')
  if (validLocale(saved)) {
    systemLocale.value = validLocale(defaultLang) ? defaultLang : 'zh-CN'
    setLocale(saved)
    return currentLocale.value
  }
  let userLanguage = ''
  const token = localStorage.getItem('filebox_token')
  if (token) {
    try {
      const response = await fetch('/api/auth/me', { headers: { Authorization: `Bearer ${token}` } })
      if (response.ok) userLanguage = (await response.json()).data?.language || ''
    } catch { /* public fallback below */ }
  }
  let resolvedDefault = defaultLang
  if (!validLocale(resolvedDefault)) {
    try {
      const response = await fetch('/api/brand')
      if (response.ok) resolvedDefault = (await response.json()).data?.defaultLang
    } catch { /* zh-CN fallback below */ }
  }
  systemLocale.value = validLocale(resolvedDefault) ? resolvedDefault : 'zh-CN'
  setLocale(validLocale(userLanguage) && userLanguage ? userLanguage : systemLocale.value)
  if (!userLanguage) localStorage.removeItem('filebox_locale')
  return currentLocale.value
}
